// lib/package-lifecycle/manifest.mjs
// PACKAGE.md generator for the package assembly engine.
// Produces a discoverable manifest with version, contents, Node >= 20 prerequisite, and quick start.
// Timestamps in Asia/Bangkok (UTC+07:00) per project rules.
// Barrel-exported.

/**
 * Generate PACKAGE.md content for an assembled Sidekicks package.
 *
 * @param {{
 *   version: string,           // Package version (from package.json or VERSION.json)
 *   includedComponents: string[],  // List of component names included (lib/*, skills/*)
 *   includesClaude: boolean,
 *   includesGemini: boolean,
 *   includesAgent: boolean,
 *   builtAt?: Date,            // Build timestamp; defaults to now
 * }} opts
 * @returns {string} PACKAGE.md content (UTF-8, no trailing newline added)
 */
export function generatePackageManifest(opts) {
  const {
    version,
    includedComponents = [],
    includesClaude = true,
    includesGemini = true,
    includesAgent = true,
    builtAt,
  } = opts;

  const now = builtAt ?? new Date();

  // Format timestamp in Asia/Bangkok (UTC+07:00)
  const timestamp = now.toLocaleString("en-US", {
    timeZone: "Asia/Bangkok",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
  }) + " (Asia/Bangkok UTC+07:00)";

  const aiContextSection = [
    includesClaude ? "- `.claude/` — Claude Code skill symlinks" : null,
    includesGemini ? "- `.gemini/` — Gemini CLI skill symlinks" : null,
    includesAgent ? "- `.agent/` — Agent CLI skill symlinks" : null,
  ]
    .filter(Boolean)
    .join("\n");

  const componentList = includedComponents.length > 0
    ? includedComponents.map((c) => `- \`${c}\``).join("\n")
    : "- (no components listed)";

  return `# Sidekicks Package — PACKAGE.md

> Generated by \`sidekicks package create\`

## Package Version

${version}

## Build Timestamp

${timestamp}

## Runtime Prerequisite

**Node.js >= 20** is required. The package uses native \`node:fs\`, \`node:path\`, and
\`node --test\` — all available in Node 20+. No npm install step is needed.

## Contents

### Core

- \`bin/sidekicks\` — zero-dependency CLI dispatcher (mode 0755)
- \`package.json\` — package manifest (type: module, no runtime deps)
- \`README.md\` — documentation
- \`AGENTS.md\` — agent bootstrap instructions
- \`CLAUDE.md\` — symlink → AGENTS.md
- \`GEMINI.md\` — symlink → AGENTS.md
- \`scripts/\` — helper scripts

### Subsystems

${componentList}

### Skills

- \`.agents/skills/\` — all bundled Sidekicks skills

### AI Context

${aiContextSection || "- (no AI context directories included)"}

### Control surface

- \`.sidekicks/RULES.md\` — boundary rules
- \`.sidekicks/settings.json\` — clean defaults (active_project: sidekicks, active_service: null)
- \`projects/.gitkeep\` — projects directory placeholder

## Quick Start

\`\`\`bash
# From the package root:
node bin/sidekicks --help

# Ensure VERSION.json for all components:
node bin/sidekicks package versions

# List all registered projects:
node bin/sidekicks project list
\`\`\`

## Notes

- This package contains no user configuration or secrets (\`config.yaml\` excluded).
- \`settings.json\` is reset to clean defaults — the package is not tied to any individual workspace.
- Skill defaults are used in the absence of a project \`config.yaml\`.
- The \`bmad/\` directory (if present) adds AI workflow support via \`--include-gemini\`.
`;
}
