// lib/core-lifecycle/_seed.mjs
// The workspace files `core init` puts in place, and the classification that decides which of them a
// re-run may overwrite (AAP-110).
//
// THREE CLASSES, borrowed from lib/package-lifecycle/overlay.mjs so a mounted workspace and a
// packaged install answer the same question the same way:
//
//   System    — framework-owned. Always rewritten on init/update (the per-CLI wiring, the bin shim).
//   User      — created once if absent, then NEVER touched (config.yaml, framework.yaml, AGENTS.md,
//               package.json, the memory store).
//   Managed   — a delimited block inside a user-owned file (.gitignore, AGENTS.md's import line).
//               Inserted when missing, refreshed in place, and never rewriting the rest of the file.
//
// Getting this wrong is the whole risk of an updater: `core update` runs unattended and must not be
// able to eat a customized workspace.
//
// Zero npm dependencies — node:* + lib/ back-edges only.

import { existsSync, readFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { writeAtomic, mkdirp } from '../fs-safety/fsx.mjs';
import { CORE_DIR } from '../sk-cli/core-mount.mjs';

/** Managed-block delimiters. Same shape as the external-project-link block in the root .gitignore. */
export const BLOCK_BEGIN = 'BEGIN sidekicks core (managed by `sidekicks core init`)';
export const BLOCK_END = 'END sidekicks core';

/**
 * The bin shim: a workspace's `bin/sidekicks` forwards into the mounted core.
 *
 * It imports the core's dispatcher directly rather than spawning it, so exit codes and stdio pass
 * through unchanged. The dispatcher resolves the repo root from `process.cwd()` and reads its version
 * from the core's own package.json — both correct here: the workspace is the root, the framework
 * version is the core's.
 *
 * @returns {string}
 */
export function binShim() {
  return `#!/usr/bin/env node
// GENERATED by \`sidekicks core init\` — do not edit; \`core update\` rewrites it.
//
// The framework lives in the ${CORE_DIR}/ submodule. This shim forwards to its dispatcher so
// \`node bin/sidekicks …\` works from the workspace root exactly as it does in a full checkout.

import { main } from "../${CORE_DIR}/lib/sk-cli/cli.mjs";

await main(process.argv.slice(2));
`;
}

/**
 * A fresh workspace AGENTS.md — the user's own instruction surface, with the framework's rules pulled
 * in by reference so `core update` refreshes them without touching anything the user wrote.
 *
 * @param {string} repoRoot
 * @param {string} frameworkDocRel - repo-relative path of the core's framework instruction file
 * @returns {string}
 */
export function workspaceAgentsMd(repoRoot, frameworkDocRel) {
  const name = basename(repoRoot);
  return `# ${name} — Agent Bootstrap

${managedBlock(frameworkDocRel)}

## About this workspace

The Sidekicks framework is mounted as a git submodule at \`${CORE_DIR}/\` and is **read-only** here:
its CLI, libraries, hook scripts and framework skills all live inside it. The block above imports the
framework's own rules, so they travel with whichever version this workspace is pinned to
(\`sidekicks core status\`).

Everything below this line is yours. Add project conventions, house style, and anything specific to
this workspace — \`core update\` never touches it.

## Working here

| What | Where |
|---|---|
| Your work | \`projects/<name>/\` |
| Your own skills | \`.agents/skills/<name>/\` (a real directory always wins over the core's) |
| Credentials and per-scope config | \`.sidekicks/config.yaml\` (git-ignored) |
| Decisions worth keeping | \`sidekicks memory add …\` |
| Framework version | \`sidekicks core status\` / \`sidekicks core update --ref <tag>\` |
`;
}

/**
 * The managed import block inserted at the top of a workspace AGENTS.md.
 *
 * `@path` is Claude Code's import syntax, and CLAUDE.md mirrors AGENTS.md, so Claude Code still sees
 * it. On a CLI without import support the line reads as an explicit pointer to the file to load.
 *
 * @param {string} frameworkDocRel
 * @returns {string}
 */
export function managedBlock(frameworkDocRel) {
  return `<!-- ${BLOCK_BEGIN} -->
@${frameworkDocRel}
<!-- ${BLOCK_END} -->`;
}

/**
 * Insert or refresh a managed block in `text`.
 *
 * @param {string} text  - current file content ('' for a new file)
 * @param {string} block - the block, including its delimiters
 * @param {'top'|'bottom'} where - placement when the block is absent
 * @returns {{text: string, changed: boolean, action: 'inserted'|'refreshed'|'unchanged'}}
 */
export function upsertBlock(text, block, where = 'top') {
  // Emit the block AND its surrounding glue in the file's own dominant line ending, rather than always
  // LF. A workspace ships no .gitattributes, so on Windows with core.autocrlf=true these files
  // legitimately live as CRLF; an LF-only insert would leave them mixed on every run. The alternative —
  // normalizing the whole file to LF — would rewrite bytes the workspace owner wrote, which is worse
  // than the problem being solved.
  //
  // Idempotence is unaffected either way: the delimiter regexes are not anchored to \n, and `.`
  // consumes a trailing \r, so a CRLF-terminated delimiter line still matches cleanly.
  const nl = text.includes('\r\n') ? '\r\n' : '\n';
  const body = nl === '\r\n' ? block.replace(/\r?\n/g, '\r\n') : block.replace(/\r\n/g, '\n');

  const beginRe = new RegExp(`^.*${escapeRe(BLOCK_BEGIN)}.*$`, 'm');
  const endRe = new RegExp(`^.*${escapeRe(BLOCK_END)}.*$`, 'm');

  const beginMatch = beginRe.exec(text);
  const endMatch = endRe.exec(text);

  if (beginMatch && endMatch && endMatch.index > beginMatch.index) {
    const before = text.slice(0, beginMatch.index);
    const after = text.slice(endMatch.index + endMatch[0].length);
    const next = before + body + after;
    return next === text
      ? { text, changed: false, action: 'unchanged' }
      : { text: next, changed: true, action: 'refreshed' };
  }

  const next = where === 'top'
    ? `${body}${nl}${nl}${text.replace(/^(\r?\n)+/, '')}`
    : `${text.replace(/(\r?\n)*$/, '')}${nl}${nl}${body}${nl}`;
  return { text: next, changed: true, action: 'inserted' };
}

function escapeRe(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Fixed lines of the managed .gitignore block, without delimiters.
 *
 * Everything here is either machine-local, a secret, or a link the CLI recreates on every run — the
 * same reasoning as the root repo's .gitignore, restated for a workspace that has no lib/ or tests/
 * of its own.
 *
 * Note what is deliberately NOT ignored: `.sidekicks/memory/`, `.sidekicks/config/framework.yaml`,
 * the committed half of every `config/<family>.yaml`, and `projects/` — all of them travel with the
 * workspace repo. Only the `config/<family>.secret.yaml` siblings stay behind.
 */
export const WORKSPACE_IGNORE = Object.freeze([
  '# Machine-local scope state — never committed. Derived state (the scope index, the running-agent',
  '# registry, the artifact inventory) lives in one directory, so new state files need no new rule.',
  '.sidekicks/state/',
  '.sidekicks/settings.json',
  '# The same files at their pre-move top-level paths, still read until a checkout migrates.',
  '.sidekicks/index.json',
  '.sidekicks/running-agents.json',
  '.sidekicks/artifacts-inventory.json',
  '.sidekicks/artifacts-inventory.md',
  '',
  '# Credentials. Configuration is a folder per scope, one file per family: the committed',
  '# config/<family>.yaml carries the structure with credential keys present but EMPTY, and its',
  '# config/<family>.secret.yaml sibling carries the values. Write both with `sidekicks config set`.',
  '.sidekicks/config/*.secret.yaml',
  'projects/*/config/*.secret.yaml',
  '',
  '# The pre-family config.yaml monolith — legacy, still read one layer lower. Ignored whole because',
  '# one credential in it made the entire file unpublishable, which is what the split above fixes.',
  '.sidekicks/config.yaml',
  'projects/*/config.yaml',
  '.env',
  'settings.local.json',
  '',
  '# Skill exposure links (Rule 3) — folder links the CLI recreates on every invocation. A committed',
  '# symlink checks out as a text stub on Windows and silently breaks skill discovery.',
  '# `.agents/skills` is deliberately ABSENT: it is the canonical tree, a real committed directory,',
  '# not a link. Listing it here would ignore every skill in the repo — a fresh clone would come up',
  '# with an empty tree while all three links still resolved into it.',
  '/.claude/skills',
  '/.agent/skills',
  '/.gemini/skills',
  '',
  '# Generated output and run state.',
  'artifacts/',
  'output/',
  'tmp/',
  '',
  '# Python / Node / OS noise.',
  '.venv/',
  '__pycache__/',
  'node_modules/',
  '.DS_Store',
  'Thumbs.db',
]);

/**
 * The .gitignore lines that exclude the overlay links, one line per LINK that actually exists.
 *
 * Two decisions, both learned the hard way:
 *
 *   - Enumeration, not a `.agents/skills/*` glob. Git cannot tell an overlay link from a skill
 *     directory the workspace author wrote, so a glob would silently stop their own skills from ever
 *     being committed.
 *   - Keyed on what is a LINK here, not on what the core ships. When a workspace authors a skill whose
 *     name the core also ships, the workspace's real directory wins (ensureCoreSkillOverlay leaves it
 *     alone) — and listing that name would then make the author's own work uncommittable.
 *
 * The list lives inside the managed block, so it refreshes on every `core init` / `core update`.
 *
 * @param {string[]} linkNames - names under <workspace>/.agents/skills that are links into the core
 * @returns {string[]}
 */
export function coreSkillIgnoreLines(linkNames) {
  if (!linkNames.length) return [];
  return [
    '',
    '# Framework skills projected out of the mounted core as folder links (Rule 3). The core is the',
    '# source of truth for them, so committing a link would duplicate an already-pinned submodule.',
    '# Listed one by one, never globbed, and only where the entry really is a link — a skill YOU',
    '# author stays committable even when it shadows a core skill of the same name.',
    ...[...linkNames].sort().map((n) => `/.agents/skills/${n}`),
  ];
}

/**
 * An empty local-memory store, matching what `sidekicks memory rebuild` would produce.
 *
 * @returns {string}
 */
export function emptyMemoryIndex() {
  return `# Local memory

Committed decision store for this workspace. Write entries with \`sidekicks memory add\` — never by
hand. One line per entry below.
`;
}

/**
 * A minimal workspace package.json. It exists so \`node\` treats .mjs consistently and so the
 * workspace has a name; it declares NO dependencies, because the framework has none.
 *
 * @param {string} repoRoot
 * @returns {string}
 */
export function workspacePackageJson(repoRoot) {
  return JSON.stringify({
    name: basename(repoRoot).toLowerCase().replace(/[^a-z0-9._-]+/g, '-'),
    version: '0.1.0',
    private: true,
    type: 'module',
    engines: { node: '>=20' },
    scripts: {
      sidekicks: 'node bin/sidekicks',
    },
  }, null, 2) + '\n';
}

/**
 * Write `content` to `abs` only when the file does not exist yet (the User class).
 *
 * @param {string} abs
 * @param {string} content
 * @returns {boolean} true when written
 */
export function writeIfAbsent(abs, content) {
  if (existsSync(abs)) return false;
  mkdirp(join(abs, '..'));
  writeAtomic(abs, content);
  return true;
}

/**
 * Write `content` unconditionally (the System class), returning whether the bytes changed.
 *
 * @param {string} abs
 * @param {string} content
 * @returns {boolean} true when the file's content changed
 */
export function writeSystem(abs, content) {
  let before = null;
  try {
    before = readFileSync(abs, 'utf8');
  } catch { /* absent */ }
  if (before === content) return false;
  mkdirp(join(abs, '..'));
  writeAtomic(abs, content);
  return true;
}
