# Sidekicks Framework — workspace bootstrap (Windows / PowerShell).
#
# GENERATED by sk-inherit at 2026-08-19T09:00:52+07:00 from source commit 9c5f447b.
# Do not edit in the framework repo: the next forge overwrites it. Change the template at
# .agents/skills/sk-inherit/assets/install.ps1.tmpl in the Sidekicks source repo.
#
# The exact twin of install.sh — same steps, same flags, same idempotence. Kept as a separate file
# rather than an OS fork of the logic: both drive the same `sidekicks core init`, which is where all
# the real work lives and which is itself cross-platform.
#
# USAGE
#   irm https://raw.githubusercontent.com/utranand/sidekicks-harness/main/install.ps1 | iex
#   # with options, download first (piping to iex cannot take arguments):
#   irm https://raw.githubusercontent.com/utranand/sidekicks-harness/main/install.ps1 -OutFile install.ps1
#   ./install.ps1 -Dir my-workspace -Ref main

[CmdletBinding()]
param(
  [string]$Dir    = 'sidekicks',
  [string]$Ref    = 'main',
  [string]$Remote = 'https://github.com/utranand/sidekicks-harness.git',
  [switch]$NoInit,
  [switch]$Help
)

$ErrorActionPreference = 'Stop'
$CoreDir = '.sidekicks-core'

function Step($m) { Write-Host ''; Write-Host "==> $m" }
function Say($m)  { Write-Host "  $m" }
function Fail($m) { Write-Error "error: $m"; exit 1 }

# Same option table install.sh prints for --help. Kept in step with the sh twin deliberately: a user
# on Windows must be able to discover the options without reading the source.
function Usage {
  Write-Host @'
Sidekicks Framework — workspace bootstrap (Windows / PowerShell).

  -Dir <path>      workspace directory (default: sidekicks)
  -Ref <ref>       framework branch or tag to pin (default: main)
  -Remote <url>    framework remote to mount (default: https://github.com/utranand/sidekicks-harness.git)
  -NoInit          mount only; skip `core init` (you run it yourself)
  -Help            print this and exit

  ./install.ps1 -Dir my-workspace -Ref main
'@
  exit 0
}

if ($Help) { Usage }

# ── Preflight ─────────────────────────────────────────────────────────────────────────────────────
Step 'checking prerequisites'

if (-not (Get-Command git -ErrorAction SilentlyContinue)) { Fail 'git is required but not on PATH' }

$nodeCmd = Get-Command node -ErrorAction SilentlyContinue
if (-not $nodeCmd) {
  foreach ($candidate in @(
    "$env:ProgramFiles\nodejs\node.exe",
    "${env:ProgramFiles(x86)}\nodejs\node.exe",
    "$env:LOCALAPPDATA\Programs\nodejs\node.exe"
  )) {
    if ($candidate -and (Test-Path $candidate)) { $nodeCmd = Get-Command $candidate; break }
  }
}
if (-not $nodeCmd) { Fail 'Node.js >= 20 is required but no node.exe was found' }
$node = $nodeCmd.Source

# Validate BEFORE the cast, matching the sh twin's `case "$NODE_MAJOR" in ''|*[!0-9]*)` guard. An nvm
# shim or a wrapper that prints a banner makes [int] throw a raw .NET conversion error instead of this
# tool's own message — a different failure mode than install.sh for the same input.
$major = & $node -e 'process.stdout.write(String(process.versions.node.split(".")[0]))'
if ("$major".Trim() -notmatch '^\d+$') { Fail "could not determine the Node.js version from $node" }
if ([int]$major -lt 20) { Fail "Node.js >= 20 is required (found $(& $node -v))" }

Say "git    $((git --version) -replace '^git version ','')"
Say "node   $(& $node -v) at $node"

# ── Workspace ─────────────────────────────────────────────────────────────────────────────────────
Step "preparing the workspace at $Dir"

New-Item -ItemType Directory -Force -Path $Dir | Out-Null
Set-Location $Dir
$ws = (Get-Location).Path

git rev-parse --git-dir 2>$null | Out-Null
if ($LASTEXITCODE -eq 0) { Say 'reusing the existing git repository' }
else { git init -q .; Say 'git init' }

# ── Mount ─────────────────────────────────────────────────────────────────────────────────────────
Step "mounting the framework core at $CoreDir"

# Check out any kind of ref — tag, branch or SHA — inside the mounted core.
# `submodule add -b` is deliberately NOT used: it accepts a BRANCH only, so a release tag makes it
# fail and leaves a half-added submodule behind. Adding first and checking out after handles all three
# ref kinds through one path, which is also what `sidekicks core update --ref` does.
function Checkout-Ref {
  git -C $CoreDir fetch --tags --quiet origin 2>$null
  git -C $CoreDir rev-parse --verify --quiet "$Ref^{commit}" 2>$null | Out-Null
  if ($LASTEXITCODE -eq 0) { git -C $CoreDir checkout --detach --quiet $Ref; return }
  git -C $CoreDir rev-parse --verify --quiet "origin/$Ref^{commit}" 2>$null | Out-Null
  if ($LASTEXITCODE -eq 0) { git -C $CoreDir checkout --detach --quiet "origin/$Ref"; return }
  Fail "'$Ref' does not resolve in the framework repo (checked as a tag, a SHA and origin/$Ref)"
}

if (Test-Path (Join-Path $CoreDir '.sidekicks-core.json')) {
  Say "already mounted — fetching and moving it to $Ref"
  Checkout-Ref
}
elseif (Test-Path $CoreDir) {
  Fail "$CoreDir already exists and is not a framework core — move it aside and re-run"
}
else {
  # protocol.file.allow=always keeps a local-path remote working under git's post-CVE-2022-39253
  # defaults, which matters for testing an unpublished framework build.
  git -c protocol.file.allow=always submodule add -q $Remote $CoreDir
  if ($LASTEXITCODE -ne 0) { Fail "could not add $Remote as a submodule at $CoreDir" }
  git -c protocol.file.allow=always submodule update --init --quiet $CoreDir 2>$null
  Checkout-Ref
}

if (-not (Test-Path (Join-Path $CoreDir 'bin/sidekicks'))) {
  Fail "the mount at $CoreDir carries no CLI — is '$Ref' a valid framework ref?"
}

# Record what this mount is meant to TRACK. Every checkout above detaches — which is what "pinned to
# a release" means — so the checkout itself remembers nothing, and `sidekicks core update` used to
# read a detached HEAD, find the literal 'HEAD', and fall through to main. Two places, on purpose:
#   - .gitmodules is COMMITTED, so a fresh clone of this workspace still knows what it tracks;
#   - the core-local key is the per-machine override.
# Parity with install.sh.tmpl (Rule 6) — keep the two in step.
git config -f .gitmodules "submodule.$CoreDir.branch" $Ref 2>$null
if ($LASTEXITCODE -ne 0) { Say 'could not record the tracked ref in .gitmodules' }
git -C $CoreDir config --local sidekicks.trackedRef $Ref 2>$null

Say "$CoreDir @ $(git -C $CoreDir rev-parse --short HEAD)  (tracking $Ref)"

# ── Seed ──────────────────────────────────────────────────────────────────────────────────────────
if ($NoInit) {
  Step 'skipping core init (-NoInit)'
  Say "finish by hand:  & '$node' $CoreDir/bin/sidekicks core init"
  exit 0
}

Step 'seeding the workspace'
& $node (Join-Path $CoreDir 'bin/sidekicks') core init
if ($LASTEXITCODE -ne 0) { Fail 'core init failed — the mount is in place; re-run it after fixing the cause' }

Step 'done'
Say "workspace:  $ws"
Write-Host ''
Say 'node bin/sidekicks --help            what the CLI can do'
Say 'node bin/sidekicks core status       which framework version you are on'
Say 'node bin/sidekicks project create <name>'
Write-Host ''
Say "The framework at $CoreDir/ is read-only: pushing from it is refused. Update it with"
Say "'node bin/sidekicks core update --ref <tag>', which stages the change without committing."
