#!/bin/sh
# Sidekicks Framework — workspace bootstrap.
#
# GENERATED by sk-inherit at 2026-08-22T23:13:44+07:00 from source commit 4c050bab.
# Do not edit in the framework repo: the next forge overwrites it. Change the template at
# .agents/skills/sk-inherit/assets/install.sh.tmpl in the Sidekicks source repo.
#
# WHAT IT DOES
#   1. Checks for git and Node >= 20.
#   2. Creates (or reuses) a workspace directory and makes it a git repo.
#   3. Mounts this framework as a READ-ONLY git submodule at .sidekicks-core/.
#   4. Runs `sidekicks core init` from inside the mount, which seeds the workspace and arms the
#      read-only push guard.
#
# Every step is idempotent: re-running over an existing workspace updates it instead of failing.
# Nothing is committed — the workspace's git history belongs to you.
#
# USAGE
#   curl -fsSL https://raw.githubusercontent.com/utranand/sidekicks-harness/main/install.sh | sh
#   curl -fsSL https://raw.githubusercontent.com/utranand/sidekicks-harness/main/install.sh | sh -s -- --dir my-workspace --ref main
#
#   --dir <path>     workspace directory (default: sidekicks)
#   --ref <ref>      framework branch or tag to pin (default: main)
#   --remote <url>   framework remote to mount (default: https://github.com/utranand/sidekicks-harness.git)
#   --no-init        mount only; skip `core init` (you run it yourself)
#   -h, --help       print this and exit
#
# POSIX sh on purpose — /bin/sh on macOS and Linux, and Git Bash on Windows. The PowerShell twin is
# install.ps1.

set -eu

CORE_DIR=".sidekicks-core"
REMOTE="https://github.com/utranand/sidekicks-harness.git"
REF="main"
DIR="sidekicks"
RUN_INIT=1

say()  { printf '%s\n' "$*"; }
step() { printf '\n==> %s\n' "$*"; }
fail() { printf 'error: %s\n' "$*" >&2; exit 1; }

usage() {
  sed -n '2,32p' "$0" 2>/dev/null | sed 's/^# \{0,1\}//'
  exit 0
}

# ── Arguments ─────────────────────────────────────────────────────────────────────────────────────
while [ $# -gt 0 ]; do
  case "$1" in
    --dir)     [ $# -ge 2 ] || fail "--dir needs a value";    DIR="$2";    shift 2 ;;
    --ref)     [ $# -ge 2 ] || fail "--ref needs a value";    REF="$2";    shift 2 ;;
    --remote)  [ $# -ge 2 ] || fail "--remote needs a value"; REMOTE="$2"; shift 2 ;;
    --dir=*)    DIR="${1#*=}";    shift ;;
    --ref=*)    REF="${1#*=}";    shift ;;
    --remote=*) REMOTE="${1#*=}"; shift ;;
    --no-init) RUN_INIT=0; shift ;;
    -h|--help) usage ;;
    *) fail "unknown option '$1' (try --help)" ;;
  esac
done

# ── Preflight ─────────────────────────────────────────────────────────────────────────────────────
step "checking prerequisites"

command -v git >/dev/null 2>&1 || fail "git is required but not on PATH"

# A GUI-launched shell or a minimal PATH can hide a perfectly good Node install, so probe the usual
# locations before giving up — the same reasoning as the framework's own pre-commit hook.
NODE=""
if command -v node >/dev/null 2>&1; then
  NODE="$(command -v node)"
else
  for candidate in \
    /opt/homebrew/bin/node \
    /usr/local/bin/node \
    /usr/bin/node \
    "$HOME/.nvm/current/bin/node" \
    /mingw64/bin/node.exe \
    "/c/Program Files/nodejs/node.exe"; do
    if [ -x "$candidate" ]; then NODE="$candidate"; break; fi
  done
fi
[ -n "$NODE" ] || fail "Node.js >= 20 is required but no 'node' executable was found"

NODE_MAJOR="$("$NODE" -e 'process.stdout.write(String(process.versions.node.split(".")[0]))' 2>/dev/null || echo 0)"
case "$NODE_MAJOR" in
  ''|*[!0-9]*) fail "could not determine the Node.js version from $NODE" ;;
esac
[ "$NODE_MAJOR" -ge 20 ] || fail "Node.js >= 20 is required (found $("$NODE" -v))"

say "  git    $(git --version | sed 's/^git version //')"
say "  node   $("$NODE" -v) at $NODE"

# ── Workspace ─────────────────────────────────────────────────────────────────────────────────────
step "preparing the workspace at $DIR"

mkdir -p "$DIR"
cd "$DIR"
WS="$(pwd)"

if [ -d .git ] || git rev-parse --git-dir >/dev/null 2>&1; then
  say "  reusing the existing git repository"
else
  git init -q .
  say "  git init"
fi

# ── Mount ─────────────────────────────────────────────────────────────────────────────────────────
step "mounting the framework core at $CORE_DIR"

# Check out any kind of ref — tag, branch or SHA — inside the mounted core.
# `submodule add -b` is deliberately NOT used: it accepts a BRANCH only, so a release tag makes it
# fail and leaves a half-added submodule behind. Adding first and checking out after handles all three
# ref kinds through one path, which is also what `sidekicks core update --ref` does.
checkout_ref() {
  git -C "$CORE_DIR" fetch --tags --quiet origin 2>/dev/null || say "  (fetch failed; using local refs)"
  if git -C "$CORE_DIR" rev-parse --verify --quiet "$REF^{commit}" >/dev/null 2>&1; then
    git -C "$CORE_DIR" checkout --detach --quiet "$REF"
  elif git -C "$CORE_DIR" rev-parse --verify --quiet "origin/$REF^{commit}" >/dev/null 2>&1; then
    git -C "$CORE_DIR" checkout --detach --quiet "origin/$REF"
  else
    fail "'$REF' does not resolve in the framework repo (checked as a tag, a SHA and origin/$REF)"
  fi
}

if [ -f "$CORE_DIR/.sidekicks-core.json" ]; then
  say "  already mounted — fetching and moving it to $REF"
  checkout_ref
elif [ -e "$CORE_DIR" ]; then
  fail "$CORE_DIR already exists and is not a framework core — move it aside and re-run"
else
  # protocol.file.allow=always keeps a file:// or local-path remote working under git's
  # post-CVE-2022-39253 defaults, which matters for testing an unpublished framework build.
  git -c protocol.file.allow=always submodule add -q "$REMOTE" "$CORE_DIR" \
    || fail "could not add $REMOTE as a submodule at $CORE_DIR"
  git -c protocol.file.allow=always submodule update --init --quiet "$CORE_DIR" 2>/dev/null || true
  checkout_ref
fi

[ -f "$CORE_DIR/bin/sidekicks" ] || fail "the mount at $CORE_DIR carries no CLI — is '$REF' a valid framework ref?"

# Record what this mount is meant to TRACK. Every checkout above detaches — which is what "pinned to
# a release" means — so the checkout itself remembers nothing, and `sidekicks core update` used to
# read a detached HEAD, find the literal 'HEAD', and fall through to main. Two places, on purpose:
#   - .gitmodules is COMMITTED, so a fresh clone of this workspace still knows what it tracks;
#   - the core-local key is the per-machine override.
git config -f .gitmodules "submodule.$CORE_DIR.branch" "$REF" 2>/dev/null \
  || say "  (could not record the tracked ref in .gitmodules)"
git -C "$CORE_DIR" config --local sidekicks.trackedRef "$REF" 2>/dev/null || true

say "  $CORE_DIR @ $(git -C "$CORE_DIR" rev-parse --short HEAD)  (tracking $REF)"

# ── Seed ──────────────────────────────────────────────────────────────────────────────────────────
if [ "$RUN_INIT" -eq 0 ]; then
  step "skipping core init (--no-init)"
  say "  finish by hand:  \"$NODE\" $CORE_DIR/bin/sidekicks core init"
  exit 0
fi

step "seeding the workspace"
"$NODE" "$CORE_DIR/bin/sidekicks" core init || fail "core init failed — the mount is in place; re-run it after fixing the cause"

step "done"
say "  workspace:  $WS"
say ""
say "  node bin/sidekicks --help            what the CLI can do"
say "  node bin/sidekicks core status       which framework version you are on"
say "  node bin/sidekicks project create <name>"
say ""
say "  The framework at $CORE_DIR/ is read-only: pushing from it is refused. Update it with"
say "  'node bin/sidekicks core update --ref <tag>', which stages the change without committing."
