#!/bin/sh
# Sidekicks Framework — workspace bootstrap.
#
# GENERATED by sk-inherit at 2026-09-04T18:16:01+07:00 from source commit af54175b.
#
# This script carries NO version of its own, deliberately. It is generic — it mounts whatever
# --ref names — and it is fetched from main so that a first-time reader with no tag yet can
# resolve it. Stamping a release into it would be a claim it cannot keep: the copy on
# main installs any release you ask it for. What you get is decided by --ref, which defaults
# to main — a moving branch, not a release. The core's README names the tag to pin.
# Do not edit in the framework repo: the next forge overwrites it. Change the template at
# .agents/skills/sk-inherit/assets/install.sh.tmpl in the Sidekicks source repo.
#
# WHAT IT DOES
#   1. Checks for git and Node >= 20.
#   2. Creates (or reuses) a workspace directory and makes it a git repo.
#   3. Mounts this framework as a READ-ONLY git submodule at .sidekicks-core/.
#   4. Runs `sidekicks core init` from inside the mount, which seeds the workspace and arms the
#      read-only push guard.
#
# Every step is idempotent: re-running over an existing workspace updates it instead of failing.
# Nothing is committed — the workspace's git history belongs to you.
#
# USAGE
#   curl -fsSL https://raw.githubusercontent.com/utranand/sidekicks-harness/main/install.sh | sh
#   curl -fsSL https://raw.githubusercontent.com/utranand/sidekicks-harness/main/install.sh | sh -s -- --dir my-workspace --ref main
#
#   --dir <path>     workspace directory (default: sidekicks)
#   --ref <ref>      framework branch or tag to pin (default: main)
#   --remote <url>   framework remote to mount (default: https://github.com/utranand/sidekicks-harness.git)
#   --no-init        mount only; skip `core init` (you run it yourself)
#   -h, --help       print this and exit
#
# POSIX sh on purpose — /bin/sh on macOS and Linux, and Git Bash on Windows. The PowerShell twin is
# install.ps1.

set -eu

CORE_DIR=".sidekicks-core"
REMOTE="https://github.com/utranand/sidekicks-harness.git"
REF="main"
DIR="sidekicks"
RUN_INIT=1

say()  { printf '%s\n' "$*"; }
step() { printf '\n==> %s\n' "$*"; }

# Set to 1 only once THIS run has added the submodule, so a failure after that point can put the
# workspace back the way it found it. Never set when the mount was already there — that one belongs
# to the user, and a failed re-point must leave it exactly as found.
MOUNT_ADDED=0

# `submodule add` leaves FIVE artifacts behind, and a partial cleanup is worse than none: missing
# .git/modules/<dir> makes the next `submodule add` die with "a git directory for '<dir>' is found
# locally", which is a third distinct misleading error on top of the two this fixes.
cleanup_mount() {
  [ "$MOUNT_ADDED" -eq 1 ] || return 0
  say "  cleaning up the partial mount so a re-run starts clean"
  git submodule deinit -f -- "$CORE_DIR" >/dev/null 2>&1 || true
  git rm -f --cached "$CORE_DIR" >/dev/null 2>&1 || true
  rm -rf "$CORE_DIR" || true
  rm -rf ".git/modules/$CORE_DIR" || true
  git config -f .gitmodules --remove-section "submodule.$CORE_DIR" >/dev/null 2>&1 || true
  # A .gitmodules this run created and then emptied is noise in `git status`, not a record — but it
  # must leave the INDEX too. `submodule add` staged it, and a file that is gone from the worktree
  # while still staged makes the next add die with "please make sure that the .gitmodules file is in
  # the working tree" — the same class of misleading second error this cleanup exists to prevent.
  if [ -f .gitmodules ] && [ ! -s .gitmodules ]; then
    git rm -f --cached .gitmodules >/dev/null 2>&1 || true
    rm -f .gitmodules
  fi
  MOUNT_ADDED=0
}

# No `trap ... EXIT`: under `set -eu` it would also fire on the success path and on usage's exit 0,
# so it needs the state variable regardless — and PowerShell has no sh-equivalent, which would break
# the byte-parallel twin (Rule 6). Funnelling through fail() is the one shape both can hold.
fail() { cleanup_mount; printf 'error: %s\n' "$*" >&2; exit 1; }

usage() {
  sed -n '2,32p' "$0" 2>/dev/null | sed 's/^# \{0,1\}//'
  exit 0
}

# ── Arguments ─────────────────────────────────────────────────────────────────────────────────────
while [ $# -gt 0 ]; do
  case "$1" in
    --dir)     [ $# -ge 2 ] || fail "--dir needs a value";    DIR="$2";    shift 2 ;;
    --ref)     [ $# -ge 2 ] || fail "--ref needs a value";    REF="$2";    shift 2 ;;
    --remote)  [ $# -ge 2 ] || fail "--remote needs a value"; REMOTE="$2"; shift 2 ;;
    --dir=*)    DIR="${1#*=}";    shift ;;
    --ref=*)    REF="${1#*=}";    shift ;;
    --remote=*) REMOTE="${1#*=}"; shift ;;
    --no-init) RUN_INIT=0; shift ;;
    -h|--help) usage ;;
    *) fail "unknown option '$1' (try --help)" ;;
  esac
done

# ── Preflight ─────────────────────────────────────────────────────────────────────────────────────
step "checking prerequisites"

command -v git >/dev/null 2>&1 || fail "git is required but not on PATH"

# A GUI-launched shell or a minimal PATH can hide a perfectly good Node install, so probe the usual
# locations before giving up — the same reasoning as the framework's own pre-commit hook.
NODE=""
if command -v node >/dev/null 2>&1; then
  NODE="$(command -v node)"
else
  for candidate in \
    /opt/homebrew/bin/node \
    /usr/local/bin/node \
    /usr/bin/node \
    "$HOME/.nvm/current/bin/node" \
    /mingw64/bin/node.exe \
    "/c/Program Files/nodejs/node.exe"; do
    if [ -x "$candidate" ]; then NODE="$candidate"; break; fi
  done
fi
[ -n "$NODE" ] || fail "Node.js >= 20 is required but no 'node' executable was found"

NODE_MAJOR="$("$NODE" -e 'process.stdout.write(String(process.versions.node.split(".")[0]))' 2>/dev/null || echo 0)"
case "$NODE_MAJOR" in
  ''|*[!0-9]*) fail "could not determine the Node.js version from $NODE" ;;
esac
[ "$NODE_MAJOR" -ge 20 ] || fail "Node.js >= 20 is required (found $("$NODE" -v))"

say "  git    $(git --version | sed 's/^git version //')"
say "  node   $("$NODE" -v) at $NODE"

# ── Workspace ─────────────────────────────────────────────────────────────────────────────────────
step "preparing the workspace at $DIR"

mkdir -p "$DIR"
cd "$DIR"
WS="$(pwd)"

if [ -d .git ] || git rev-parse --git-dir >/dev/null 2>&1; then
  say "  reusing the existing git repository"
else
  git init -q .
  say "  git init"
fi

# ── Mount ─────────────────────────────────────────────────────────────────────────────────────────
step "mounting the framework core at $CORE_DIR"

# Check out any kind of ref — tag, branch or SHA — inside the mounted core.
# `submodule add -b` is deliberately NOT used: it accepts a BRANCH only, so a release tag makes it
# fail and leaves a half-added submodule behind. Adding first and checking out after handles all three
# ref kinds through one path, which is also what `sidekicks core update --ref` does.
checkout_ref() {
  FETCHED=1
  git -C "$CORE_DIR" fetch --tags --quiet origin 2>/dev/null || {
    FETCHED=0
    say "  (fetch failed; using local refs)"
  }
  # Both checkouts are `|| fail`, not bare: a bare command inside an if/elif BODY aborts the script
  # under `set -e` WITHOUT reaching fail(), which would leave behind the very half-added mount the
  # cleanup exists to remove.
  if git -C "$CORE_DIR" rev-parse --verify --quiet "$REF^{commit}" >/dev/null 2>&1; then
    git -C "$CORE_DIR" checkout --detach --quiet "$REF" || fail "could not check out '$REF' in $CORE_DIR"
  elif git -C "$CORE_DIR" rev-parse --verify --quiet "origin/$REF^{commit}" >/dev/null 2>&1; then
    git -C "$CORE_DIR" checkout --detach --quiet "origin/$REF" \
      || fail "could not check out 'origin/$REF' in $CORE_DIR"
  else
    # An unresolvable ref used to print the same line whether the tag was never pushed or the network
    # was down, and then left a half-added submodule that made the RE-RUN fail differently again.
    # Say which world this is, show what does resolve, and hand back a command that works.
    if [ "$FETCHED" -eq 0 ]; then
      say ""
      say "  the fetch from origin FAILED, so only refs already cloned locally could be checked."
      say "  '$REF' may well exist on the remote — check the network or your credentials first."
    else
      say ""
      say "  the remote was reached, and it does not serve '$REF'."
      # --refs drops the ^{} peeled duplicates, which is what makes this list readable. Deliberately
      # unsorted: `sort -V` is not POSIX, and a plain sort puts v1.10.0 before v1.9.0.
      TAGS="$(git -C "$CORE_DIR" ls-remote --tags --refs origin 2>/dev/null | sed 's#.*refs/tags/##')"
      if [ -n "$TAGS" ]; then
        say ""
        say "  tags the remote does serve:"
        printf '    %s\n' $TAGS
      else
        say "  (could not list the remote's tags — no network?)"
      fi
    fi
    say ""
    say "  to install the newest framework on the default branch instead:"
    say "    curl -fsSL https://raw.githubusercontent.com/utranand/sidekicks-harness/main/install.sh | sh -s -- --ref main"
    say ""
    fail "'$REF' does not resolve in the framework repo (checked as a tag, a SHA and origin/$REF)"
  fi
}

if [ -f "$CORE_DIR/.sidekicks-core.json" ]; then
  say "  already mounted — fetching and moving it to $REF"
  checkout_ref
elif [ -e "$CORE_DIR" ]; then
  fail "$CORE_DIR already exists and is not a framework core — move it aside and re-run"
else
  # protocol.file.allow=always keeps a file:// or local-path remote working under git's
  # post-CVE-2022-39253 defaults, which matters for testing an unpublished framework build.
  git -c protocol.file.allow=always submodule add -q "$REMOTE" "$CORE_DIR" \
    || fail "could not add $REMOTE as a submodule at $CORE_DIR"
  MOUNT_ADDED=1
  git -c protocol.file.allow=always submodule update --init --quiet "$CORE_DIR" 2>/dev/null || true
  checkout_ref
fi

[ -f "$CORE_DIR/bin/sidekicks" ] || fail "the mount at $CORE_DIR carries no CLI — is '$REF' a valid framework ref?"

# The mount is good from here on, so it stops being this run's to undo. Without this, `core init`
# failing below would delete .sidekicks-core/ while printing "the mount is in place" — a message that
# would be a lie, and a cleanup that destroys a working mount over a re-runnable seeding error.
MOUNT_ADDED=0

# Record what this mount is meant to TRACK. Every checkout above detaches — which is what "pinned to
# a release" means — so the checkout itself remembers nothing, and `sidekicks core update` used to
# read a detached HEAD, find the literal 'HEAD', and fall through to main. Two places, on purpose:
#   - .gitmodules is COMMITTED, so a fresh clone of this workspace still knows what it tracks;
#   - the core-local key is the per-machine override.
#
# The `git add` is not optional and is not tidiness. `submodule add` staged .gitmodules BEFORE this
# key existed, so without re-staging, `git commit` (no -a) records a pin whose tracked ref is absent
# from the committed file — the exact thing the line above claims it prevents. A fresh clone then
# reads no branch key and `core update` falls back to main, silently retargeting the workspace.
git config -f .gitmodules "submodule.$CORE_DIR.branch" "$REF" 2>/dev/null \
  || say "  (could not record the tracked ref in .gitmodules)"
git add .gitmodules 2>/dev/null \
  || say "  (could not stage .gitmodules — 'git add .gitmodules' by hand before committing)"
git -C "$CORE_DIR" config --local sidekicks.trackedRef "$REF" 2>/dev/null || true

say "  $CORE_DIR @ $(git -C "$CORE_DIR" rev-parse --short HEAD)  (tracking $REF)"

# ── Seed ──────────────────────────────────────────────────────────────────────────────────────────
if [ "$RUN_INIT" -eq 0 ]; then
  step "skipping core init (--no-init)"
  say "  finish by hand:  \"$NODE\" $CORE_DIR/bin/sidekicks core init"
  exit 0
fi

step "seeding the workspace"
"$NODE" "$CORE_DIR/bin/sidekicks" core init || fail "core init failed — the mount is in place; re-run it after fixing the cause"

step "done"
say "  workspace:  $WS"
say ""
say "  node bin/sidekicks --help            what the CLI can do"
say "  node bin/sidekicks core status       which framework version you are on"
say "  node bin/sidekicks project create <name>"
say ""
say "  The framework at $CORE_DIR/ is read-only: pushing from it is refused. Update it with"
say "  'node bin/sidekicks core update --ref <tag>', which stages the change without committing."
