# Sidekicks Framework — workspace bootstrap (Windows / PowerShell).
#
# GENERATED by sk-inherit at 2026-09-04T11:08:14+07:00 from source commit dcf15e16.
#
# This script carries NO version of its own, deliberately. It is generic — it mounts whatever
# -Ref names — and it is fetched from main so that a first-time reader with no tag yet can
# resolve it. Stamping a release into it would be a claim it cannot keep: the copy on
# main installs any release you ask it for. What you get is decided by -Ref, which defaults
# to main — a moving branch, not a release. The core's README names the tag to pin.
# Do not edit in the framework repo: the next forge overwrites it. Change the template at
# .agents/skills/sk-inherit/assets/install.ps1.tmpl in the Sidekicks source repo.
#
# The exact twin of install.sh — same steps, same flags, same idempotence. Kept as a separate file
# rather than an OS fork of the logic: both drive the same `sidekicks core init`, which is where all
# the real work lives and which is itself cross-platform.
#
# USAGE
#   irm https://raw.githubusercontent.com/utranand/sidekicks-harness/main/install.ps1 | iex
#   # with options, download first (piping to iex cannot take arguments):
#   irm https://raw.githubusercontent.com/utranand/sidekicks-harness/main/install.ps1 -OutFile install.ps1
#   ./install.ps1 -Dir my-workspace -Ref main

[CmdletBinding()]
param(
  [string]$Dir    = 'sidekicks',
  [string]$Ref    = 'main',
  [string]$Remote = 'https://github.com/utranand/sidekicks-harness.git',
  [switch]$NoInit,
  [switch]$Help
)

$ErrorActionPreference = 'Stop'
$CoreDir = '.sidekicks-core'

function Step($m) { Write-Host ''; Write-Host "==> $m" }
function Say($m)  { Write-Host "  $m" }

# Parity with install.sh.tmpl (Rule 6). Set to $true only once THIS run added the submodule, so a
# failure after that point can put the workspace back as it found it. Never set for a mount that was
# already there — that one belongs to the user.
$script:MountAdded = $false

# `submodule add` leaves five artifacts; a partial cleanup makes the NEXT run fail with a third,
# different error ("a git directory for '<dir>' is found locally").
function Cleanup-Mount {
  if (-not $script:MountAdded) { return }
  Say 'cleaning up the partial mount so a re-run starts clean'
  git submodule deinit -f -- $CoreDir 2>$null | Out-Null
  git rm -f --cached $CoreDir 2>$null | Out-Null
  $modules = Join-Path '.git/modules' $CoreDir
  foreach ($p in @($CoreDir, $modules)) {
    if (Test-Path $p) {
      try {
        Remove-Item -Recurse -Force $p -ErrorAction Stop
      } catch {
        # Git writes pack files read-only and a just-exited git process may still hold a handle, so
        # this really can fail on Windows. Say so and name the command — never claim a cleanup that
        # did not happen, because the next run's error would then be inexplicable.
        Say "could NOT remove $p — delete it by hand before re-running:"
        Say "    rmdir /s /q `"$p`""
      }
    }
  }
  git config -f .gitmodules --remove-section "submodule.$CoreDir" 2>$null | Out-Null
  # Must leave the INDEX too, not just the worktree: `submodule add` staged .gitmodules, and a file
  # that is gone from the worktree while still staged makes the next add die with "please make sure
  # that the .gitmodules file is in the working tree".
  if ((Test-Path '.gitmodules') -and -not (Get-Content '.gitmodules' -Raw -ErrorAction SilentlyContinue)) {
    git rm -f --cached .gitmodules 2>$null | Out-Null
    Remove-Item -Force '.gitmodules' -ErrorAction SilentlyContinue
  }
  $script:MountAdded = $false
}

# No try/finally around the whole script: it would also run on the success path, and it would stop
# this file being a line-for-line twin of install.sh.tmpl, which has no `trap EXIT` available either.
function Fail($m) { Cleanup-Mount; Write-Error "error: $m"; exit 1 }

# Same option table install.sh prints for --help. Kept in step with the sh twin deliberately: a user
# on Windows must be able to discover the options without reading the source.
function Usage {
  Write-Host @'
Sidekicks Framework — workspace bootstrap (Windows / PowerShell).

  -Dir <path>      workspace directory (default: sidekicks)
  -Ref <ref>       framework branch or tag to pin (default: main)
  -Remote <url>    framework remote to mount (default: https://github.com/utranand/sidekicks-harness.git)
  -NoInit          mount only; skip `core init` (you run it yourself)
  -Help            print this and exit

  ./install.ps1 -Dir my-workspace -Ref main
'@
  exit 0
}

if ($Help) { Usage }

# ── Preflight ─────────────────────────────────────────────────────────────────────────────────────
Step 'checking prerequisites'

if (-not (Get-Command git -ErrorAction SilentlyContinue)) { Fail 'git is required but not on PATH' }

$nodeCmd = Get-Command node -ErrorAction SilentlyContinue
if (-not $nodeCmd) {
  foreach ($candidate in @(
    "$env:ProgramFiles\nodejs\node.exe",
    "${env:ProgramFiles(x86)}\nodejs\node.exe",
    "$env:LOCALAPPDATA\Programs\nodejs\node.exe"
  )) {
    if ($candidate -and (Test-Path $candidate)) { $nodeCmd = Get-Command $candidate; break }
  }
}
if (-not $nodeCmd) { Fail 'Node.js >= 20 is required but no node.exe was found' }
$node = $nodeCmd.Source

# Validate BEFORE the cast, matching the sh twin's `case "$NODE_MAJOR" in ''|*[!0-9]*)` guard. An nvm
# shim or a wrapper that prints a banner makes [int] throw a raw .NET conversion error instead of this
# tool's own message — a different failure mode than install.sh for the same input.
$major = & $node -e 'process.stdout.write(String(process.versions.node.split(".")[0]))'
if ("$major".Trim() -notmatch '^\d+$') { Fail "could not determine the Node.js version from $node" }
if ([int]$major -lt 20) { Fail "Node.js >= 20 is required (found $(& $node -v))" }

Say "git    $((git --version) -replace '^git version ','')"
Say "node   $(& $node -v) at $node"

# ── Workspace ─────────────────────────────────────────────────────────────────────────────────────
Step "preparing the workspace at $Dir"

New-Item -ItemType Directory -Force -Path $Dir | Out-Null
Set-Location $Dir
$ws = (Get-Location).Path

git rev-parse --git-dir 2>$null | Out-Null
if ($LASTEXITCODE -eq 0) { Say 'reusing the existing git repository' }
else { git init -q .; Say 'git init' }

# ── Mount ─────────────────────────────────────────────────────────────────────────────────────────
Step "mounting the framework core at $CoreDir"

# Check out any kind of ref — tag, branch or SHA — inside the mounted core.
# `submodule add -b` is deliberately NOT used: it accepts a BRANCH only, so a release tag makes it
# fail and leaves a half-added submodule behind. Adding first and checking out after handles all three
# ref kinds through one path, which is also what `sidekicks core update --ref` does.
function Checkout-Ref {
  git -C $CoreDir fetch --tags --quiet origin 2>$null
  $fetched = ($LASTEXITCODE -eq 0)
  git -C $CoreDir rev-parse --verify --quiet "$Ref^{commit}" 2>$null | Out-Null
  if ($LASTEXITCODE -eq 0) { git -C $CoreDir checkout --detach --quiet $Ref; return }
  git -C $CoreDir rev-parse --verify --quiet "origin/$Ref^{commit}" 2>$null | Out-Null
  if ($LASTEXITCODE -eq 0) { git -C $CoreDir checkout --detach --quiet "origin/$Ref"; return }

  # An unresolvable ref used to print the same line whether the tag was never pushed or the network
  # was down, and then left a half-added submodule. Say which world this is and show what resolves.
  Write-Host ''
  if (-not $fetched) {
    Say "the fetch from origin FAILED, so only refs already cloned locally could be checked."
    Say "'$Ref' may well exist on the remote — check the network or your credentials first."
  } else {
    Say "the remote was reached, and it does not serve '$Ref'."
    # --refs drops the ^{} peeled duplicates. Deliberately unsorted, matching the sh twin.
    $tags = git -C $CoreDir ls-remote --tags --refs origin 2>$null
    if ($LASTEXITCODE -eq 0 -and $tags) {
      Write-Host ''
      Say 'tags the remote does serve:'
      foreach ($t in $tags) { Write-Host ('    ' + ($t -replace '.*refs/tags/', '')) }
    } else {
      Say '(could not list the remote''s tags — no network?)'
    }
  }
  Write-Host ''
  Say 'to install the newest framework on the default branch instead:'
  Say '    ./install.ps1 -Ref main'
  Write-Host ''
  Fail "'$Ref' does not resolve in the framework repo (checked as a tag, a SHA and origin/$Ref)"
}

if (Test-Path (Join-Path $CoreDir '.sidekicks-core.json')) {
  Say "already mounted — fetching and moving it to $Ref"
  Checkout-Ref
}
elseif (Test-Path $CoreDir) {
  Fail "$CoreDir already exists and is not a framework core — move it aside and re-run"
}
else {
  # protocol.file.allow=always keeps a local-path remote working under git's post-CVE-2022-39253
  # defaults, which matters for testing an unpublished framework build.
  git -c protocol.file.allow=always submodule add -q $Remote $CoreDir
  if ($LASTEXITCODE -ne 0) { Fail "could not add $Remote as a submodule at $CoreDir" }
  $script:MountAdded = $true
  git -c protocol.file.allow=always submodule update --init --quiet $CoreDir 2>$null
  Checkout-Ref
}

if (-not (Test-Path (Join-Path $CoreDir 'bin/sidekicks'))) {
  Fail "the mount at $CoreDir carries no CLI — is '$Ref' a valid framework ref?"
}

# Parity with install.sh.tmpl (Rule 6): the mount is good from here on, so it stops being this run's
# to undo. Without this, a `core init` failure below would delete the mount while printing "the mount
# is in place".
$script:MountAdded = $false

# Record what this mount is meant to TRACK. Every checkout above detaches — which is what "pinned to
# a release" means — so the checkout itself remembers nothing, and `sidekicks core update` used to
# read a detached HEAD, find the literal 'HEAD', and fall through to main. Two places, on purpose:
#   - .gitmodules is COMMITTED, so a fresh clone of this workspace still knows what it tracks;
#   - the core-local key is the per-machine override.
#
# The `git add` is not optional and is not tidiness. `submodule add` staged .gitmodules BEFORE this
# key existed, so without re-staging, `git commit` (no -a) records a pin whose tracked ref is absent
# from the committed file — the exact thing the line above claims it prevents. A fresh clone then
# reads no branch key and `core update` falls back to main, silently retargeting the workspace.
# Parity with install.sh.tmpl (Rule 6) — keep the two in step.
git config -f .gitmodules "submodule.$CoreDir.branch" $Ref 2>$null
if ($LASTEXITCODE -ne 0) { Say 'could not record the tracked ref in .gitmodules' }
git add .gitmodules 2>$null
if ($LASTEXITCODE -ne 0) { Say "could not stage .gitmodules - 'git add .gitmodules' by hand before committing" }
git -C $CoreDir config --local sidekicks.trackedRef $Ref 2>$null

Say "$CoreDir @ $(git -C $CoreDir rev-parse --short HEAD)  (tracking $Ref)"

# ── Seed ──────────────────────────────────────────────────────────────────────────────────────────
if ($NoInit) {
  Step 'skipping core init (-NoInit)'
  Say "finish by hand:  & '$node' $CoreDir/bin/sidekicks core init"
  exit 0
}

Step 'seeding the workspace'
& $node (Join-Path $CoreDir 'bin/sidekicks') core init
if ($LASTEXITCODE -ne 0) { Fail 'core init failed — the mount is in place; re-run it after fixing the cause' }

Step 'done'
Say "workspace:  $ws"
Write-Host ''
Say 'node bin/sidekicks --help            what the CLI can do'
Say 'node bin/sidekicks core status       which framework version you are on'
Say 'node bin/sidekicks project create <name>'
Write-Host ''
Say "The framework at $CoreDir/ is read-only: pushing from it is refused. Update it with"
Say "'node bin/sidekicks core update --ref <tag>', which stages the change without committing."
