// lib/config-lifecycle/sync.mjs
// `sidekicks config sync [--scope <name>] [--only a,b] [--dry-run] [--check] [--refresh] [--prune] [--json]`
//
// THE RESCAN VERB. It walks every installed skill's `config:` declaration — not a catalog — and
// makes sure each declared block is documented in the scope's family file, seeded from the skill's
// own `config.defaults.yaml`. Adding or enhancing a skill therefore changes what this generates
// with no list to maintain anywhere.
//
// It is the CONFIGURATION half of a pair. The SETTINGS half — the boolean enable map in
// `.sidekicks/config/settings/` — is `framework sync`, which this verb also runs at the end so one
// command leaves both halves complete. See docs/guide/settings-vs-configuration.md.
//
// GENERATED BLOCKS ARE COMMENTED OUT, AND THAT IS THE WHOLE SAFETY MODEL.
// Writing live default values into a scope's family file would make that file SHADOW the skill's
// defaults: the skill later improves a default, and the scope silently keeps the old value forever
// because a higher layer now carries it. Emitting the block inert means
//   - the file documents the schema, so a fresh clone can see what is configurable;
//   - the block still resolves to the OWNING SKILL's defaults until a human uncomments a key,
//     which is exactly the "fall back to the skill if not configured" contract;
//   - uncommenting is an explicit, reviewable override.
// This is the stance sk-hello's config-init.mjs took against the pre-family monolith. That
// script is retired and this verb replaced it: a structural write under `.sidekicks/` belongs to
// the CLI (Rule 1), not to a skill's bundled script, and a second implementation of the resolution
// chain living inside a skill is how that skill's audit came to report every configured connector
// in this repo as unconfigured.
//
// THREE ACTIONS, IN STRICT ORDER OF SAFETY:
//   add      the family file lacks the block entirely            → appended, inert
//   refresh  the block is present but VALUE-FREE (scaffold)      → regenerated; opt-in via --refresh
//   keep     the block carries live values                       → NEVER touched, in any mode.
//            Keys the current defaults document that the live block lacks are REPORTED as drift
//            for a human to merge. A live config may hold real credentials; rewriting it is not a
//            risk worth any convenience.
// Nothing is ever deleted. `--prune` MOVES an undeclared block to `pending-removal.<family>.yaml`
// (git-ignored) rather than dropping it.
//
// Zero npm dependencies — node:* + lib/ back-edges only.

import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { EXIT_OK, EXIT_USAGE, EXIT_VALIDATION, SidekicksError } from '../sk-cli/errors.mjs';
import { read as readSettings } from '../settings-store/settings.mjs';
import { resolveEffectiveScope } from '../active-scope/scope.mjs';
import { buildFamilies, CONFIG_DIR, LEGACY_FILE } from '../config-store/families.mjs';
import { blockFromFile } from '../config-store/block.mjs';
import { topLevelKeyLines } from '../config-store/lint.mjs';
import {
  PENDING_PREFIX,
  ensurePendingIgnore,
  ensureSecretIgnore,
  removeBlock,
  renderBody,
  splitSecrets,
  writeBlock,
} from '../config-store/write.mjs';
import { writeAtomic } from '../fs-safety/fsx.mjs';
import { assertWritable } from '../fs-safety/fs-guard.mjs';
import { materializeFramework, frameworkDrift } from '../framework-settings/materialize.mjs';
import { parseConfigFlags } from './_shared.mjs';

/** Marker written above every generated region, and the way a later run recognises its own work. */
const BANNER_RULE = '#'.repeat(78);
const BANNER_TEXT = 'Generated by `sidekicks config sync` from the installed skills\' '
  + 'config.defaults.yaml.';

/** The header a family file this verb creates from scratch carries. */
function familyHeader(family, file) {
  return [
    `# ${file} — the '${family}' configuration family (COMMITTED).`,
    '#',
    '# CONFIGURATION, not settings: values. The boolean enable map lives in',
    '# .sidekicks/config/settings/. See docs/guide/settings-vs-configuration.md.',
    '#',
    '# Credentials NEVER live here. Every credential key appears with an empty value so a fresh',
    `# clone can see what to supply; the values go in the git-ignored '${family}.secret.yaml'`,
    '# sibling. Write with `sidekicks config set`, read with `sidekicks config get <block>`.',
    '#',
    '# A block that is present but entirely commented out is INERT: it documents the schema, and',
    '# the block still resolves to the owning skill\'s config.defaults.yaml until a key is',
    '# uncommented here.',
  ];
}

// ---------------------------------------------------------------------------
// Reading what a scope already has
// ---------------------------------------------------------------------------

/** Is every leaf of this value empty (''/null/{}/[])? Such a block decides nothing. */
function isValueFree(value) {
  if (value === null || value === undefined || value === '') return true;
  if (Array.isArray(value)) return value.every(isValueFree);
  if (typeof value === 'object') return Object.values(value).every(isValueFree);
  return false;
}

/**
 * A commented-out block this verb (or its predecessor) generated, located in the file's lines.
 *
 * The region starts at `# <block>:` in column 0 and runs while the following lines are comments
 * that are NOT another top-level `# <key>:` — i.e. the block's own indented body and any blank
 * comment lines inside it. A non-comment line ends it.
 *
 * @param {string[]} lines
 * @param {string} block
 * @returns {{start: number, end: number}|null} inclusive line indices
 */
function commentedRegion(lines, block) {
  const startRe = new RegExp(`^#\\s?${block}\\s*:`);
  const otherTop = /^#\s?[A-Za-z][A-Za-z0-9_-]*\s*:/;
  for (let i = 0; i < lines.length; i++) {
    if (!startRe.test(lines[i])) continue;
    let end = i;
    for (let j = i + 1; j < lines.length; j++) {
      const line = lines[j];
      if (!line.startsWith('#')) break;      // a real line ends the region
      if (otherTop.test(line)) break;        // the next generated block starts
      end = j;
    }
    return { start: i, end };
  }
  return null;
}

/**
 * What state a block is in inside one family file.
 *
 * @returns {'absent'|'scaffold'|'live'}
 */
function blockStatus(repoRoot, relPath, entry) {
  const abs = join(repoRoot, relPath);
  if (!existsSync(abs)) return 'absent';
  const live = blockFromFile(abs, relPath, entry.block, entry.aliases);
  if (live !== null) return isValueFree(live) ? 'scaffold' : 'live';
  const lines = readFileSync(abs, 'utf8').split(/\r?\n/);
  if (commentedRegion(lines, entry.block)) return 'scaffold';
  for (const alias of entry.aliases) {
    if (commentedRegion(lines, alias)) return 'scaffold';
  }
  return 'absent';
}

/** Dotted key paths a defaults value documents that a live block does not carry. */
function missingKeys(defaults, live, prefix = '') {
  const out = [];
  if (!defaults || typeof defaults !== 'object' || Array.isArray(defaults)) return out;
  for (const [key, value] of Object.entries(defaults)) {
    const path = prefix ? `${prefix}.${key}` : key;
    const has = live && typeof live === 'object' && !Array.isArray(live)
      && Object.prototype.hasOwnProperty.call(live, key);
    if (!has) { out.push(path); continue; }
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      out.push(...missingKeys(value, live[key], path));
    }
  }
  return out;
}

// ---------------------------------------------------------------------------
// Scopes
// ---------------------------------------------------------------------------

/**
 * Which scope bases this run targets.
 *
 * Unlike `config doctor`'s enumeration, `--scope all` includes a project that has NO configuration
 * yet: seeding the scope that lacks everything is the point of the verb, so filtering on "already
 * has a config/ directory" would skip exactly the case worth running.
 *
 * @param {string} repoRoot
 * @param {string} wanted - 'active' | 'root' | 'all' | a project name
 * @returns {Array<{scope: string, base: string}>}
 */
function targetScopes(repoRoot, wanted) {
  const root = { scope: 'sidekicks', base: '.sidekicks' };
  if (wanted === 'root') return [root];

  const projects = [];
  const projectsDir = join(repoRoot, 'projects');
  if (existsSync(projectsDir)) {
    let entries = [];
    try { entries = readdirSync(projectsDir, { withFileTypes: true }); } catch { entries = []; }
    for (const dirent of entries) {
      if (!dirent.isDirectory() && !dirent.isSymbolicLink()) continue;
      const base = join('projects', dirent.name);
      // A project is a project when it carries a manifest — the same definition the rest of the
      // CLI uses. A bare directory under projects/ is not a scope.
      if (!existsSync(join(repoRoot, base, 'manifest.yaml'))) continue;
      projects.push({ scope: dirent.name, base });
    }
  }

  if (wanted === 'all') return [root, ...projects];

  if (wanted === 'active') {
    const { projectName, projectRelPath } = resolveEffectiveScope(readSettings(repoRoot));
    if (!projectRelPath) return [root];
    return [{ scope: projectName, base: projectRelPath }];
  }

  const named = projects.find((p) => p.scope === wanted);
  if (!named) {
    throw new SidekicksError(
      `config sync: no project '${wanted}' — pass 'active', 'root', 'all', or a project name `
      + `(${projects.map((p) => p.scope).join(', ') || 'none found'})`,
      EXIT_VALIDATION
    );
  }
  return [named];
}

// ---------------------------------------------------------------------------
// Planning
// ---------------------------------------------------------------------------

/**
 * Decide, without writing anything, what each declared block needs in one scope.
 *
 * @param {string} repoRoot
 * @param {{scope: string, base: string}} target
 * @param {Array<object>} blocks - the merged block registry
 * @param {{refresh: boolean, prune: boolean}} opts
 */
function planScope(repoRoot, target, blocks, opts) {
  const isRoot = target.base === '.sidekicks';
  const items = [];

  for (const entry of blocks) {
    // `--only` narrows the run to the blocks the user actually asked for.
    const named = !opts.only
      || opts.only.has(entry.block) || entry.aliases.some((a) => opts.only.has(a));
    if (!named) continue;

    // A root-scoped block is infrastructure the framework reads at root only — generating it into
    // a project would document a file nothing there will ever read. Naming it under `--only` does
    // not change that, but it does change the reporting: silence would read as "done", so the
    // block is listed as skipped with the reason. Asking for it is a mistake worth seeing.
    if (!isRoot && entry.scope === 'root') {
      if (opts.only) {
        items.push({
          block: entry.block, family: entry.family,
          file: join(target.base, CONFIG_DIR, entry.file), action: 'skip',
          why: 'root-scoped: the framework reads this block at root only, so documenting it in a '
            + 'project would describe a file nothing there reads — run with --scope root',
          missing: [], defaults_from: null,
        });
      }
      continue;
    }

    // The inverse, and it exists for the same reason: a project-scoped block is configured per
    // project, so generating it into the ROOT scope would document a file nothing will ever read
    // there -- and, worse, invite someone to fill it in where the resolver does not look. Reported
    // as skipped under `--only` so silence cannot read as "done".
    if (isRoot && entry.scope === 'project') {
      if (opts.only) {
        items.push({
          block: entry.block, family: entry.family,
          file: join(target.base, CONFIG_DIR, entry.file), action: 'skip',
          why: 'project-scoped: this block is configured per project, so documenting it at root '
            + 'would describe a file the resolver never reads -- run with --scope <project>',
          missing: [], defaults_from: null,
        });
      }
      continue;
    }

    const defaultsRel = entry.defaults_from
      ? join(entry.defaults_from.tree, entry.defaults_from.skill, entry.defaults_from.file)
      : null;
    const defaults = defaultsRel
      ? blockFromFile(join(repoRoot, defaultsRel), defaultsRel, entry.block, entry.aliases)
      : null;
    const seed = defaults ?? entry.builtin;

    const familyRel = join(target.base, CONFIG_DIR, entry.file);
    const status = blockStatus(repoRoot, familyRel, entry);

    if (!seed) {
      // Nothing to write. `defaults-missing` is the doctor's finding, not this verb's job; here it
      // is simply a block that cannot be seeded.
      items.push({
        block: entry.block, family: entry.family, file: familyRel, action: 'skip',
        why: 'the owning skill ships no config.defaults.yaml and declares no builtin',
        missing: [], defaults_from: defaultsRel,
      });
      continue;
    }

    if (status === 'live') {
      const live = blockFromFile(join(repoRoot, familyRel), familyRel, entry.block, entry.aliases);
      const missing = missingKeys(seed, live);
      items.push({
        block: entry.block, family: entry.family, file: familyRel, action: 'keep',
        // Not-overridden is NOT broken: an absent key resolves from the owning skill's defaults,
        // which is the contract. It is reported because the defaults may have grown keys worth
        // knowing about — a prompt to look, never a repair the verb should make.
        why: missing.length
          ? `carries live values — never rewritten; ${missing.length} key(s) the defaults `
            + 'document are not overridden here (they resolve from the skill)'
          : 'carries live values — never rewritten',
        missing, defaults_from: defaultsRel, seed,
      });
      continue;
    }

    if (status === 'scaffold') {
      items.push({
        block: entry.block, family: entry.family, file: familyRel,
        action: opts.refresh ? 'refresh' : 'skip',
        why: opts.refresh
          ? 'scaffold only (no live value) — regenerated from the current defaults'
          : 'scaffold already present — pass --refresh to regenerate it from the current defaults',
        missing: [], defaults_from: defaultsRel, seed, entry,
      });
      continue;
    }

    items.push({
      block: entry.block, family: entry.family, file: familyRel, action: 'add',
      why: 'declared by an installed skill, absent here',
      missing: [], defaults_from: defaultsRel, seed, entry,
    });
  }

  items.sort((a, b) => a.file.localeCompare(b.file) || a.block.localeCompare(b.block));
  // Orphans are found on EVERY run, not only under --prune: a block nothing declares any more is
  // worth naming the moment it is noticed. Only the acting on it is opt-in.
  //
  // A NARROWED run reports none. An orphan sweep is a statement about the whole scope, and making
  // it from a run that looked at four blocks would name as orphans the blocks the user simply did
  // not ask about.
  return { ...target, items, orphans: opts.only ? [] : findOrphans(repoRoot, target, blocks) };
}

/**
 * Top-level keys in a scope's family files that no registered block (or alias) claims.
 *
 * The legacy monolith is deliberately NOT scanned: `config migrate` owns that file, and a block
 * still sitting there is mid-migration, not an orphan.
 */
function findOrphans(repoRoot, target, blocks) {
  const claimed = new Set();
  for (const b of blocks) {
    claimed.add(b.block);
    for (const alias of b.aliases) claimed.add(alias);
  }
  const byFile = new Map();
  for (const b of blocks) byFile.set(b.file, b.family);

  const dirRel = join(target.base, CONFIG_DIR);
  const dirAbs = join(repoRoot, dirRel);
  if (!existsSync(dirAbs)) return [];
  let names = [];
  try { names = readdirSync(dirAbs); } catch { return []; }

  const out = [];
  for (const name of names) {
    // Only real family files: never a secret sibling, a parked monolith, or the settings directory.
    if (!name.endsWith('.yaml')) continue;
    if (name.endsWith('.secret.yaml') || name.startsWith(PENDING_PREFIX)) continue;
    if (!byFile.has(name)) continue;
    const rel = join(dirRel, name);
    let text = '';
    try { text = readFileSync(join(repoRoot, rel), 'utf8'); } catch { continue; }
    for (const { key } of topLevelKeyLines(text)) {
      if (claimed.has(key)) continue;
      out.push({ block: key, file: rel, family: byFile.get(name) });
    }
  }
  out.sort((a, b) => a.file.localeCompare(b.file) || a.block.localeCompare(b.block));
  return out;
}

// ---------------------------------------------------------------------------
// Applying
// ---------------------------------------------------------------------------

/** One block rendered as an inert, fully commented region. */
function renderInert(block, value) {
  const body = renderBody(value, 1);
  // A block whose defaults are deliberately empty (`confluence: {}` — keyed by an alias nobody can
  // guess) must still say so explicitly, the same way renderBody spells a nested empty mapping.
  // A bare `# confluence:` would read as a truncated block rather than an intentional one.
  if (!body.length) return [`# ${block}: {}`];
  // renderBody returns LINES, not a string — every one of them gets the comment marker, so the
  // whole region is inert and the file still parses as if the block were absent.
  const lines = [`# ${block}:`];
  for (const line of body) lines.push(line === '' ? '#' : `# ${line}`);
  return lines;
}

/**
 * Apply one scope's plan. One read-modify-write per family file, so a file is never seen
 * half-updated by anything else.
 */
function applyScope(repoRoot, plan, blocks, prune) {
  const byFile = new Map();
  for (const item of plan.items) {
    if (item.action !== 'add' && item.action !== 'refresh') continue;
    if (!byFile.has(item.file)) byFile.set(item.file, []);
    byFile.get(item.file).push(item);
  }

  const written = [];
  for (const [rel, items] of byFile) {
    const abs = join(repoRoot, rel);
    const exists = existsSync(abs);
    const before = exists ? readFileSync(abs, 'utf8') : '';
    const crlf = /\r\n/.test(before);
    // Normalise to LF for every mutation and convert back exactly once on write. Skipping the
    // read-side normalisation turns each existing \r\n into \r\r\n — corrupting the whole file on
    // the commonest path there is (an add-only run against a CRLF config).
    let lines = exists
      ? before.replace(/\r\n/g, '\n').replace(/\n$/, '').split('\n')
      : familyHeader(items[0].family, rel.split(/[\\/]/).pop());

    // Refresh first, bottom-up, so earlier line ranges stay valid as the array shifts.
    const refreshes = items
      .filter((i) => i.action === 'refresh')
      .map((i) => ({ item: i, region: commentedRegion(lines, i.block) }))
      .filter((r) => r.region !== null)
      .sort((a, b) => b.region.start - a.region.start);
    for (const r of refreshes) {
      lines.splice(
        r.region.start,
        r.region.end - r.region.start + 1,
        ...renderInert(r.item.block, r.item.seed)
      );
    }

    // A refresh whose region could not be located (a LIVE-but-value-free block, which has real
    // YAML lines rather than a comment region) is left for the human: rewriting real lines is the
    // one thing this verb never does.
    const adds = items.filter((i) => i.action === 'add');
    if (adds.length) {
      while (lines.length && lines[lines.length - 1].trim() === '') lines.pop();
      lines.push('', BANNER_RULE, `# ${BANNER_TEXT}`, '# Uncomment a key to override the skill\'s default.', BANNER_RULE);
      for (const item of adds) {
        lines.push('');
        lines.push(...renderInert(item.block, item.seed));
      }
    }

    const next = lines.join('\n') + '\n';
    const out = crlf ? next.replace(/\n/g, '\r\n') : next;
    if (out === before) continue;
    assertWritable(abs, repoRoot);
    writeAtomic(abs, out);
    written.push(rel);
  }

  // The git-ignored credential siblings: a skeleton of exactly the credential keys the defaults
  // document, so a fresh clone has somewhere obvious to put them.
  //
  // INERT, LIKE THE FAMILY FILE, AND FOR A SHARPER REASON. A LIVE `api_token: ""` here is a real
  // key in the ROOT-CONFIG group, and mergeGroups gives the first group carrying a key ownership of
  // it — so an empty placeholder would SHADOW whatever the owning skill's defaults say, and the
  // block's own source would read `root-config` when nothing was ever configured. Commented out, it
  // documents where the credential goes and changes nothing until `config set --secret` writes a
  // real one.
  const secrets = [];
  for (const item of plan.items) {
    // Any block the scope has not configured itself, not just the ones added on THIS run: a repo
    // whose family files were scaffolded before the credential skeleton existed would otherwise
    // never get one, because the block is no longer an `add`. `keep` is excluded — a scope that
    // carries live values manages its own credentials.
    if (!item.seed || item.action === 'keep') continue;
    const entry = blocks.find((b) => b.block === item.block);
    if (!entry) continue;
    const { secret } = splitSecrets(item.seed, entry.public_keys);
    if (!Object.keys(secret).length) continue;

    const secretRel = join(plan.base, CONFIG_DIR, entry.secret);
    const secretAbs = join(repoRoot, secretRel);
    const exists = existsSync(secretAbs);
    // Never rewrite a file that may hold a real credential, and never re-add a block it already
    // documents (live or commented).
    if (exists && blockStatus(repoRoot, secretRel, entry) !== 'absent') continue;

    const before = exists ? readFileSync(secretAbs, 'utf8') : '';
    const crlf = /\r\n/.test(before);
    const lines = exists
      ? before.replace(/\r\n/g, '\n').replace(/\n$/, '').split('\n')
      : [
        `# ${entry.secret} — CREDENTIALS ONLY, and GIT-IGNORED.`,
        '#',
        `# The committed '${entry.file}' beside this file carries the structure with every`,
        '# credential key present but empty; the values belong here. Uncomment a key and fill it in,',
        '# or let `sidekicks config set <block>.<key> <value> --secret` write it for you.',
      ];
    while (lines.length && lines[lines.length - 1].trim() === '') lines.pop();
    lines.push('');
    lines.push(...renderInert(item.block, secret));

    const next = lines.join('\n') + '\n';
    const out = crlf ? next.replace(/\n/g, '\r\n') : next;
    assertWritable(secretAbs, repoRoot);
    writeAtomic(secretAbs, out);
    secrets.push(secretRel);
  }
  if (written.length || secrets.length) {
    ensureSecretIgnore(repoRoot, join(plan.base, CONFIG_DIR));
  }

  // Prune: an undeclared block is MOVED to the parked file, never dropped. Its value may be the
  // only remaining record of how something was configured.
  const pruned = [];
  const orphansByFile = new Map();
  for (const orphan of (prune ? plan.orphans : [])) {
    if (!orphansByFile.has(orphan.file)) orphansByFile.set(orphan.file, []);
    orphansByFile.get(orphan.file).push(orphan);
  }
  for (const [rel, orphans] of orphansByFile) {
    const abs = join(repoRoot, rel);
    let text = readFileSync(abs, 'utf8');
    const name = rel.split(/[\\/]/).pop();
    const parkedRel = join(plan.base, CONFIG_DIR, `${PENDING_PREFIX}${name}`);
    for (const orphan of orphans) {
      const value = blockFromFile(abs, rel, orphan.block, []);
      if (value === null) continue;
      writeBlock(repoRoot, parkedRel, orphan.block, value, {
        header: [
          `# ${PENDING_PREFIX}${name} — blocks 'sidekicks config sync --prune' moved out of`,
          `# ${name} because no installed skill declares them any more. GIT-IGNORED.`,
          '#',
          '# Nothing reads this file. It exists so a value is never destroyed by a prune: restore a',
          '# block by declaring it again in the owning skill, then paste it back.',
        ],
      });
      text = removeBlock(text, orphan.block);
      pruned.push(orphan.block);
    }
    assertWritable(abs, repoRoot);
    writeAtomic(abs, text);
    ensurePendingIgnore(repoRoot, join(plan.base, CONFIG_DIR));
  }

  return { written, secrets, pruned };
}

// ---------------------------------------------------------------------------
// Verb
// ---------------------------------------------------------------------------

/**
 * Run `config sync`.
 *
 * @param {{ repoRoot: string, argv: string[], flags: object }} ctx
 * @param {object} _args - unused
 * @returns {Promise<{ stdout: string, exitCode: number }>}
 */
export async function run(ctx, _args) {
  const { repoRoot } = ctx;
  const flags = parseConfigFlags(ctx.argv, ['check', 'dry-run', 'refresh', 'prune', 'json']);
  const checkOnly = flags.check === true;
  // `--dry-run` and `--check` both write nothing, and they are NOT the same thing.
  //   --check    is the CI gate: it exits non-zero when a sync would close a gap.
  //   --dry-run  is the plan a human approves before it runs: same output, always exit 0.
  // Collapsing them would make the interactive walkthrough fail on the very state it exists to
  // report, which is how an approval step turns into an error nobody reads.
  const dryRun = flags['dry-run'] === true;
  const refresh = flags.refresh === true;
  const prune = flags.prune === true;
  const readOnly = checkOnly || dryRun;

  if (checkOnly && dryRun) {
    throw new SidekicksError(
      'config sync: --check and --dry-run both write nothing — use --check for the CI gate '
      + '(non-zero on a gap) or --dry-run for the plan (always exit 0), not both',
      EXIT_VALIDATION
    );
  }
  if (checkOnly && (refresh || prune)) {
    throw new SidekicksError(
      'config sync: --check writes nothing, so it cannot be combined with --refresh or --prune',
      EXIT_VALIDATION
    );
  }

  // `--only=jira,slack` narrows the run to named blocks. This is what makes the verb usable in a
  // guided first-time setup: a docs-only project may want two connectors and nothing else, and
  // documenting all thirty would bury the two it asked for.
  // PRESENT-BUT-EMPTY is an error, not "no narrowing". `--only=` reaching here as '' would
  // otherwise fall back to a full sync — the user asked to narrow and got the opposite, silently.
  const given = flags.only !== undefined;
  const only = given
    ? new Set(String(flags.only).split(',').map((s) => s.trim()).filter(Boolean))
    : null;
  if (only && !only.size) {
    throw new SidekicksError(
      "config sync: --only needs at least one block name, e.g. --only=jira,slack "
      + "(run 'sidekicks config list' to see them)",
      EXIT_USAGE
    );
  }

  const wanted = flags.scope ? String(flags.scope) : 'active';
  const targets = targetScopes(repoRoot, wanted);
  const { blocks } = buildFamilies(repoRoot);

  if (only) {
    const known = new Set(blocks.flatMap((b) => [b.block, ...b.aliases]));
    const unknown = [...only].filter((name) => !known.has(name));
    if (unknown.length) {
      throw new SidekicksError(
        `config sync: --only names ${unknown.length} block(s) nothing declares: ${unknown.join(', ')} `
        + "— run 'sidekicks config list' to see the declared blocks",
        EXIT_VALIDATION
      );
    }
  }

  const plans = targets.map((t) => planScope(repoRoot, t, blocks, { refresh, prune, only }));
  const applied = readOnly ? [] : plans.map((p) => applyScope(repoRoot, p, blocks, prune));

  // The SETTINGS half. One command leaves both halves of `config/` complete — except under
  // `--only`, which is a request about named CONFIGURATION blocks; materialising the enable map
  // there would write files the user did not ask about in a run they narrowed on purpose.
  const settings = readOnly || only
    ? frameworkDrift(repoRoot)
    : materializeFramework(repoRoot, { prune });

  const totals = { add: 0, refresh: 0, keep: 0, skip: 0, drift: 0, orphans: 0 };
  for (const plan of plans) {
    for (const item of plan.items) {
      totals[item.action] = (totals[item.action] ?? 0) + 1;
      if (item.missing.length) totals.drift += 1;
    }
    totals.orphans += plan.orphans.length;
  }

  // What FAILS --check is only what a command can fix: a declared block absent from the scope, or
  // a framework entry unlisted in the settings files. Drift inside a live block is a human merge —
  // failing CI on it would block on something no command may safely resolve.
  const drifted = totals.add > 0 || (checkOnly ? settings.missing.length > 0 : false);

  if (flags.json) {
    const payload = {
      ok: !drifted,
      checked: checkOnly,
      dry_run: dryRun,
      only: only ? [...only] : null,
      scopes: plans.map((p, i) => ({
        scope: p.scope,
        base: p.base,
        items: p.items.map((it) => ({
          block: it.block,
          family: it.family,
          file: it.file,
          action: it.action,
          why: it.why,
          missing_keys: it.missing,
          defaults_from: it.defaults_from,
        })),
        orphans: p.orphans,
        written: applied[i] ? applied[i].written : [],
        secrets: applied[i] ? applied[i].secrets : [],
        pruned: applied[i] ? applied[i].pruned : [],
      })),
      settings: (readOnly || only)
        ? { listed: settings.listed.length, toggleable: settings.toggleable, missing: settings.missing }
        : { added: settings.added, pruned: settings.pruned, path: settings.path },
      totals,
    };
    return {
      stdout: JSON.stringify(payload, null, 2) + '\n',
      exitCode: drifted && checkOnly ? EXIT_VALIDATION : EXIT_OK,
    };
  }

  const out = [];
  const SYMBOL = { add: '+', refresh: '~', keep: '=', skip: '.' };

  if (checkOnly) {
    if (!drifted) {
      out.push(`config sync --check: OK (${totals.keep} configured, ${totals.skip} documented, `
        + `${settings.listed.length}/${settings.toggleable} settings entries listed)`);
    } else {
      const lines = [];
      for (const plan of plans) {
        for (const item of plan.items) {
          if (item.action !== 'add') continue;
          lines.push(`  ${item.file}: '${item.block}' is declared by `
            + `${item.defaults_from ? item.defaults_from.split(/[\\/]/).slice(-2, -1)[0] : 'a skill'} `
            + 'but absent here');
        }
      }
      for (const id of settings.missing) lines.push(`  settings: '${id}' is not listed`);
      throw new SidekicksError(
        `config sync --check: ${lines.length} gap(s) a sync would close:\n${lines.join('\n')}\n`
        + "Run 'sidekicks config sync' to document them (blocks are written inert — they keep "
        + 'resolving to the owning skill\'s defaults until a key is uncommented).',
        EXIT_VALIDATION
      );
    }
    if (totals.drift) {
      out.push(`  note:    ${totals.drift} live block(s) do not override every key the current `
        + 'defaults document — run without --check to see which');
    }
    return { stdout: out.join('\n') + '\n', exitCode: EXIT_OK };
  }

  for (let i = 0; i < plans.length; i++) {
    const plan = plans[i];
    // A dry run applied nothing, so there is no result to render — the plan IS the output.
    const result = applied[i] || { written: [], secrets: [], pruned: [] };
    out.push(`config sync${dryRun ? ' --dry-run' : ''}: ${plan.scope} `
      + `(${join(plan.base, CONFIG_DIR)})`);
    for (const item of plan.items) {
      // Silence the already-correct on a full run — but never on a NARROWED one. `--only=jira`
      // that prints nothing reads as "found nothing", when it means "jira is configured and
      // healthy". The user named the block; answer about it.
      if (!only && item.action === 'keep' && !item.missing.length) continue;
      out.push(`  ${SYMBOL[item.action] ?? '?'} ${item.block.padEnd(28)} ${item.why}`);
      for (const key of item.missing) out.push(`      not overridden: ${key}`);
    }
    if (result.written.length) out.push(`  wrote:  ${result.written.join(', ')}`);
    if (result.secrets.length) out.push(`  seeded: ${result.secrets.join(', ')} (git-ignored)`);
    if (result.pruned.length) {
      out.push(`  parked: ${result.pruned.length} undeclared block(s) moved to `
        + `${PENDING_PREFIX}* — ${result.pruned.join(', ')}`);
    }
    if (plan.orphans.length && !prune) {
      out.push(`  NOTE: ${plan.orphans.length} block(s) here are declared by nothing `
        + `(${plan.orphans.map((o) => o.block).join(', ')}). Re-run with --prune to park them.`);
    }
  }

  if (dryRun) {
    out.push('');
    out.push('DRY RUN — nothing was written. Re-run without --dry-run to perform this plan.');
  } else if (only) {
    // A narrowed run deliberately leaves the settings half alone. Saying so beats a reader
    // assuming a plain `config sync` already happened.
    out.push(`settings: not touched — --only narrowed this run to `
      + `${[...only].join(', ')}; run 'sidekicks config sync' for the enable map`);
  } else {
    out.push(`settings: ${settings.added.length
      ? `listed ${settings.added.length} new entr(ies) in ${settings.path}`
      : 'already complete'}`);
  }
  if (!only && !dryRun && settings.unmigrated && settings.unmigrated.length) {
    out.push(`  NOTE: ${settings.unmigrated.length} id(s) still live only in the pre-split `
      + "monolith — 'sidekicks framework sync --split' moves them.");
  }

  return { stdout: out.join('\n') + '\n', exitCode: EXIT_OK };
}

// LEGACY_FILE is imported for the orphan-scan comment above; referenced here so a reader scanning
// for it finds the reason it is deliberately NOT scanned.
export const NOT_SCANNED_BY_PRUNE = LEGACY_FILE;
