// lib/goal-lifecycle/render.mjs
// The human-readable face of a machine-authoritative plan.
//
// `plan.json` is what the engine executes; `implementation-plan.md` is what a person reads before
// approving it. The two are never edited independently — this module DERIVES the markdown from the
// JSON, so a plan cannot say one thing to the operator and another to the runner. That is also why
// the digest is printed in the document: the thing being approved is identified inside the thing
// being read.
//
// WHAT THE APPROVAL SUMMARY SHOWS is chosen by one test: would a reasonable operator's answer change
// if this were hidden? Routing and tiers change cost and blast radius. Write roots and per-checkout
// base commits change what can be touched. The hard-stopped action classes change what the approval
// does NOT authorize. Budgets change how long it can run unattended. All are shown; nothing about the
// approval is left to be discovered afterwards.
//
// Pure string building — no filesystem, no clock. Zero npm dependencies.

/**
 * Render `implementation-plan.md` from an approved-shape plan.
 *
 * @param {object} plan
 * @param {{runId: string, planDigest: string, envelopeDigest?: string|null,
 *          createdAt?: string|null, contest?: object|null, order?: string[]}} meta
 * @returns {string}
 */
export function renderPlanMarkdown(plan, meta) {
  const lines = [];
  const nodes = Array.isArray(plan?.nodes) ? plan.nodes : [];
  const order = Array.isArray(meta.order) && meta.order.length
    ? meta.order
    : nodes.map((n) => n.id);
  const byId = new Map(nodes.map((n) => [n.id, n]));

  lines.push('---');
  lines.push(`run_id: ${meta.runId}`);
  lines.push(`plan_digest: ${meta.planDigest}`);
  if (meta.envelopeDigest) lines.push(`approval_envelope_digest: ${meta.envelopeDigest}`);
  if (meta.createdAt) lines.push(`created_at: ${meta.createdAt}`);
  lines.push('generated_from: plan.json');
  lines.push('---');
  lines.push('');
  lines.push('# Implementation plan');
  lines.push('');
  lines.push(
    '> Generated from `plan.json`, which is what the engine executes. Do not edit this file to change '
    + 'the plan — it is a rendering, and the digest above is what approval binds.',
  );
  lines.push('');
  lines.push('## Goal');
  lines.push('');
  lines.push(String(plan?.goal ?? '(none stated)'));
  lines.push('');

  if (Array.isArray(plan?.assumptions) && plan.assumptions.length) {
    lines.push('## Assumptions');
    lines.push('');
    for (const a of plan.assumptions) lines.push(`- ${a}`);
    lines.push('');
  }

  if (Array.isArray(plan?.decisions) && plan.decisions.length) {
    lines.push('## Decisions');
    lines.push('');
    for (const d of plan.decisions) {
      lines.push(`- **${d.choice}** — ${d.why}`);
      if (Array.isArray(d.rejected) && d.rejected.length) {
        lines.push(`  - rejected: ${d.rejected.join('; ')}`);
      }
    }
    lines.push('');
  }

  lines.push('## Nodes');
  lines.push('');
  lines.push('Executed one at a time, in this order. A node completes only when every criterion below');
  lines.push('is met with concrete evidence, judged by a fresh reviewer that did not write the code.');
  lines.push('');
  lines.push('| # | node | title | depends on | executor · tier | paths |');
  lines.push('|---:|---|---|---|---|---|');
  order.forEach((id, i) => {
    const n = byId.get(id);
    if (!n) return;
    const deps = (Array.isArray(n.depends_on) ? n.depends_on : []).join(', ') || '—';
    const paths = (Array.isArray(n.affected_paths) ? n.affected_paths : []).join('<br>') || '—';
    const complexity = n.complexity && n.complexity !== 'normal' ? ` (${n.complexity})` : '';
    lines.push(
      `| ${i + 1} | \`${id}\` | ${n.title} | ${deps} | ${n.executor} · ${n.tier}${complexity} | ${paths} |`,
    );
  });
  lines.push('');

  for (const id of order) {
    const n = byId.get(id);
    if (!n) continue;
    lines.push(`### ${id} — ${n.title}`);
    lines.push('');
    lines.push(`- **work dir:** \`${n.work_dir ?? '.'}\``);
    lines.push(`- **routed to:** ${n.executor} at the ${n.tier} tier`);
    if (Array.isArray(n.depends_on) && n.depends_on.length) {
      lines.push(`- **depends on:** ${n.depends_on.join(', ')}`);
    }
    lines.push('');
    lines.push('Acceptance criteria:');
    lines.push('');
    for (const c of Array.isArray(n.acceptance) ? n.acceptance : []) {
      lines.push(`- \`${c.id}\` — ${c.text}`);
    }
    lines.push('');
    if (Array.isArray(n.tests) && n.tests.length) {
      lines.push('Tests:');
      lines.push('');
      for (const t of n.tests) lines.push(`- \`${t}\``);
      lines.push('');
    }
  }

  if (Array.isArray(plan?.risks) && plan.risks.length) {
    lines.push('## Risks');
    lines.push('');
    for (const r of plan.risks) lines.push(`- ${r}`);
    lines.push('');
  }

  lines.push('## Out of scope');
  lines.push('');
  const oos = Array.isArray(plan?.out_of_scope) ? plan.out_of_scope : [];
  if (oos.length === 0) {
    lines.push('_Nothing declared out of scope. That is itself a finding: a plan that excludes nothing');
    lines.push('has not been bounded._');
  } else {
    for (const o of oos) lines.push(`- ${o}`);
  }
  lines.push('');

  if (meta.contest) {
    lines.push(renderContestScoreboard(meta.contest));
    lines.push('');
  }

  return `${lines.join('\n')}\n`;
}

/**
 * The approval prompt: everything binding, in the order an operator decides in.
 *
 * @param {{runId: string, envelope: object, envelopeDigest: string, planPath: string,
 *          contest?: object|null}} input
 * @returns {string}
 */
export function renderApprovalSummary(input) {
  const e = input.envelope || {};
  const lines = [];
  lines.push(`goal run ${input.runId} — ready for approval`);
  lines.push('');
  lines.push(`  plan:      ${input.planPath}`);
  lines.push(`  scope:     project ${e.scope?.project ?? '?'}${e.scope?.service ? ` · service ${e.scope.service}` : ''}`);
  lines.push('');
  lines.push('  checkouts that will receive writes (branch @ approved base commit):');
  for (const c of e.checkouts || []) {
    lines.push(`    ${c.path}  ${c.branch} @ ${String(c.base_commit).slice(0, 12)}`);
  }
  lines.push('');
  lines.push(`  write roots:   ${(e.write_roots || []).join(', ') || '(none)'}`);
  lines.push('');
  lines.push('  routing (approving the plan approves WHO runs it):');
  for (const r of e.routing || []) {
    lines.push(`    ${r.node}  ${r.executor} · ${r.tier}${r.family ? ` (${r.family})` : ''} · ${r.role}`);
  }
  lines.push('');
  const b = e.budgets || {};
  lines.push(
    `  budgets:       ${b.max_attempts_per_node} attempts/node · breaker at `
    + `${b.max_consecutive_failures} consecutive failures`
    + `${b.max_total_attempts ? ` · ${b.max_total_attempts} attempts total` : ''}`
    + `${b.max_wall_clock_ms_per_attempt ? ` · ${Math.round(b.max_wall_clock_ms_per_attempt / 1000)}s per attempt` : ''}`,
  );
  lines.push('');
  lines.push('  NOT authorized by this approval — each pauses for its own, separate grant:');
  lines.push(`    ${(e.action_policy?.hard_stopped || []).join(', ') || '(none declared — that is a bug)'}`);
  lines.push('');
  if (input.contest) {
    lines.push(renderContestScoreboard(input.contest));
    lines.push('');
  }
  lines.push(`  approval envelope digest: ${input.envelopeDigest}`);
  lines.push('');
  lines.push('  Read the plan, then approve exactly this digest:');
  lines.push(`    sidekicks goal approve ${input.runId} --digest ${input.envelopeDigest}`);
  lines.push('');
  lines.push('  Any change to the plan, routing, write roots, base commits, policy or criterion');
  lines.push('  ownership changes that digest and clears approval.');
  return `${lines.join('\n')}\n`;
}

/**
 * The contest scoreboard — families, resolved tiers, scores, disqualifications, and every graft the
 * synthesis pass accepted or rejected.
 *
 * Shown at approval time because the operator is approving a plan that was ASSEMBLED: which family
 * wrote it, who judged it, and what was grafted in from a runner-up are all part of what they are
 * being asked to trust.
 *
 * @param {object} contest
 * @returns {string}
 */
export function renderContestScoreboard(contest) {
  const lines = [];
  lines.push('## Plan contest');
  lines.push('');
  if (contest.degraded_reason) {
    lines.push(`Ran as a single planner. Reason: ${contest.degraded_reason}`);
    return lines.join('\n');
  }
  lines.push('| family | executor · tier | model | score | verdict |');
  lines.push('|---|---|---|---:|---|');
  for (const c of contest.candidates || []) {
    const score = c.score == null ? '—' : String(c.score);
    const verdict = c.disqualified
      ? `disqualified: ${c.disqualified}`
      : (c.winner ? '**winner**' : 'scored');
    lines.push(`| ${c.family} | ${c.executor} · ${c.tier} | ${c.model ?? '—'} | ${score} | ${verdict} |`);
  }
  lines.push('');
  if (Array.isArray(contest.judges) && contest.judges.length) {
    lines.push('Judging was cross-family — no seat scored a candidate from its own family, and');
    lines.push('candidates were family-anonymized before scoring:');
    lines.push('');
    for (const j of contest.judges) {
      lines.push(`- ${j.candidate_family} judged by ${j.judge_family} (${j.judge_executor} · ${j.judge_tier})`);
    }
    lines.push('');
  }
  const decisions = contest.synthesis?.decisions;
  if (Array.isArray(decisions) && decisions.length) {
    lines.push('Synthesis grafted onto the winning plan:');
    lines.push('');
    for (const d of decisions) {
      lines.push(`- ${d.accepted ? 'ACCEPTED' : 'rejected'} — ${d.what} (from ${d.source_family}): ${d.why}`);
    }
    lines.push('');
  } else if (contest.synthesis) {
    lines.push(`Synthesis: ${contest.synthesis.note || 'no grafts accepted; the winning plan stands as written'}`);
    lines.push('');
  }
  return lines.join('\n');
}

/**
 * The `goal status` report.
 *
 * @param {{state: object, runDir: string, lease: object, stopPresent: boolean}} input
 * @returns {string}
 */
export function renderStatus(input) {
  const s = input.state || {};
  const lines = [];
  lines.push(`goal run ${s.run_id} — ${s.phase}`);
  lines.push('');
  lines.push(`  run folder:  ${input.runDir}`);
  lines.push(`  updated:     ${s.updated_at ?? '?'}  (transition #${s.sequence ?? 0})`);
  lines.push(`  approved:    ${s.approved_envelope_digest ? s.approved_envelope_digest.slice(0, 16) + '…' : 'NOT APPROVED'}`);
  if (Array.isArray(s.approvals) && s.approvals.length > 1) {
    lines.push(`               ${s.approvals.length} approvals recorded (initial + amendments)`);
  }
  lines.push('');

  const nodes = Object.entries(s.nodes || {});
  if (nodes.length) {
    lines.push('  nodes:');
    for (const [id, rec] of nodes) {
      const attempts = `${rec.attempt_count ?? 0} attempt(s)`;
      const err = rec.last_error ? ` — ${rec.last_error}` : '';
      lines.push(`    ${id.padEnd(12)} ${String(rec.state).padEnd(10)} ${attempts}${err}`);
    }
    lines.push('');
  }

  const spent = s.spent || {};
  lines.push(
    `  spent:       ${spent.attempts ?? 0} attempts · ${Math.round((spent.wall_clock_ms ?? 0) / 1000)}s`
    + `${spent.tokens != null ? ` · ${spent.tokens} tokens` : ''}`
    + `${spent.usd != null ? ` · $${Number(spent.usd).toFixed(4)}` : ''}`,
  );
  if (spent.tokens == null) {
    lines.push('               (token/cost figures are best-effort — not every CLI reports them, and');
    lines.push('                the enforced budget floors are attempts and wall clock)');
  }
  lines.push(`  breaker:     ${s.breaker?.consecutive_failures ?? 0} consecutive failures`);
  lines.push('');

  lines.push(`  lease:       ${input.lease.state}${input.lease.owner ? ` (pid ${input.lease.owner.pid} on ${input.lease.owner.hostname})` : ''}`);
  if (input.lease.state === 'foreign' || input.lease.state === 'malformed') {
    lines.push(`               ${input.lease.reason}`);
  }
  lines.push(`  STOP file:   ${input.stopPresent ? 'PRESENT — no new attempt will be dispatched' : 'absent'}`);

  if (s.divergence) {
    lines.push('');
    lines.push(`  DIVERGED:    ${s.divergence.code} on '${s.divergence.event}' at ${s.divergence.observed_at}`);
    lines.push(`               ${s.divergence.error}`);
    lines.push("               run.json remains authoritative; 'goal resume' reconciles.");
  }

  if (s.needs_user) {
    lines.push('');
    lines.push(`  NEEDS YOU:   ${s.needs_user.reason}`);
    for (const f of s.needs_user.findings || []) lines.push(`               - ${f}`);
    if (s.needs_user.next) lines.push(`               next: ${s.needs_user.next}`);
  }

  if (s.action_request) {
    lines.push('');
    lines.push(`  ACTION HELD: ${s.action_request.action_class} → ${s.action_request.target ?? '?'}`);
    lines.push(`               ${s.action_request.reason ?? ''}`);
    lines.push(`               grant only this one: sidekicks goal approve-action ${s.run_id} `
      + `${s.action_request.request_id ?? '<request-id>'} --digest ${s.action_request.digest}`);
  }

  if (s.final) {
    lines.push('');
    lines.push(`  final:       ${s.final.result} at ${s.final.at}`);
    if (s.final.summary) lines.push(`               ${s.final.summary}`);
  }

  if (s.planning?.contest) {
    lines.push('');
    lines.push(renderContestScoreboard(s.planning.contest).split('\n').map((l) => `  ${l}`).join('\n'));
  }

  return `${lines.join('\n')}\n`;
}
