// lib/sk-cli/help.mjs
// VERBS metadata table (single source) and help renderer.
// The sk-cli skill derives from this shape structurally, so fields MUST NOT be renamed.
// The `status` field is data-driven and rendered verbatim into help output.

/** @type {ReadonlyArray<{namespace: string, verb: string, args: string, summary: string, status: string}>} */
export const VERBS = Object.freeze([
  { namespace: "project", verb: "create",     args: "<name>",           summary: "Scaffold a new project and activate it",                      status: "implemented" },
  { namespace: "project", verb: "list",        args: "",                 summary: "List all projects (active marked with *)",                    status: "implemented" },
  { namespace: "project", verb: "use",         args: "<name>",           summary: "Set the active project (writes .sidekicks/settings.json)",   status: "implemented" },
  { namespace: "project", verb: "current",     args: "",                 summary: "Print the effective active project (defaults to 'sidekicks')",status: "implemented" },
  { namespace: "project", verb: "remove",      args: "<name> [--force]", summary: "Permanently delete a project tree",                          status: "implemented" },
  { namespace: "project", verb: "set-remote",  args: "<git-url>",        summary: "Initialize git repo + record remote (offline, no commit)",   status: "implemented" },
  { namespace: "project", verb: "add",         args: "<git-url> [<name>]",summary: "Acquire an existing repo as a project + stage it as a root submodule",status: "implemented" },
  { namespace: "project", verb: "link",        args: "<path> [<name>]",  summary: "Link an existing out-of-tree directory (e.g. external drive) as a project via symlink/junction",status: "implemented" },
  { namespace: "project", verb: "unlink",      args: "<name>",           summary: "Remove an external project's link + .gitignore entry (leaves the external contents intact)",status: "implemented" },
  { namespace: "service", verb: "add",         args: "<name> [<git-url>]",summary: "Register a service (creates docs/, records remote; does NOT pull code)",status: "implemented" },
  { namespace: "service", verb: "pull",        args: "[<service-name>] [<branch>]", summary: "Acquire a registered service's code into src/ on demand (branch defaults to main)", status: "implemented" },
  { namespace: "service", verb: "free",        args: "[<service-name>] [--force]", summary: "Reclaim disk by deleting src/ (keeps registration; verifies git status first)", status: "implemented" },
  { namespace: "service", verb: "sync",        args: "[<service-name>]", summary: "Re-read git state and update service.yaml branch/commit",    status: "implemented" },
  { namespace: "service", verb: "checkout",    args: "<branch> [<service-name>] [--create] [--allow-dirty]", summary: "Switch/create a branch in the service and update service.yaml (refuses a dirty tree — --allow-dirty overrides)", status: "implemented" },
  { namespace: "service", verb: "remove",      args: "<service-name> [--force]", summary: "Delete a service tree + deregister its submodule",     status: "implemented" },
  { namespace: "service", verb: "use",         args: "<service-name>",   summary: "Set the active service for the active project",              status: "implemented" },
  { namespace: "service", verb: "current",     args: "",                 summary: "Print the active service or '(none)'",                       status: "implemented" },
  { namespace: "branch",  verb: "list",        args: "",                 summary: "List local branches of the active scope's repo (current marked with *)", status: "implemented" },
  { namespace: "branch",  verb: "current",     args: "",                 summary: "Print the checked-out branch of the active scope's repo",    status: "implemented" },
  { namespace: "branch",  verb: "create",      args: "<name> [--switch] [--allow-dirty]", summary: "Create a branch in the active scope's repo (--switch to check it out — refuses a dirty tree)", status: "implemented" },
  { namespace: "branch",  verb: "switch",      args: "<branch> [--create] [--allow-dirty]", summary: "Switch the active scope's repo to a branch (--create to make it); syncs service.yaml; refuses a dirty tree", status: "implemented" },
  { namespace: "branch",  verb: "delete",      args: "<name> [--force]", summary: "Delete a branch in the active scope's repo (--force for unmerged)", status: "implemented" },
  { namespace: "scope",   verb: "working-folder", args: "",              summary: "Print the absolute working folder (service src/) for the active scope — where CODE lands", status: "implemented" },
  { namespace: "scope",   verb: "artifacts-base", args: "",              summary: "Print the absolute base dir that generated artifacts/runs anchor to (service ROOT, not src/)", status: "implemented" },
  { namespace: "scope",   verb: "run-base",       args: "<skill-id> [<work-item>] [--bare] [--json]", summary: "Print the v2 run base: <project>/artifacts/runs/<work-item>/<facet> (--bare drops the facet; no work item → _adhoc/<skill-id>)", status: "implemented" },
  { namespace: "scope",   verb: "inventory",      args: "[--project <p>] [--service <s>] [--json]", summary: "Git-derived file inventory for a scope (files, count, top dirs, tech hint)", status: "implemented" },
  { namespace: "index",   verb: "rebuild",        args: "[<project>]",   summary: "Rebuild and persist the root index (and all project indexes), or only a named project's index", status: "implemented" },
  { namespace: "index",   verb: "show",           args: "[<project>] [--json]", summary: "Print root registry or a project's service index; --json emits machine-readable output", status: "implemented" },
  { namespace: "index",   verb: "get",            args: "<key>",        summary: "Resolve one index entry by key (active, project:<p>, skills, project:<p>:service:<s>)", status: "implemented" },
  { namespace: "framework", verb: "list",    args: "[--json] [--kind <rule|criterion|hook>] [--disabled]", summary: "List every framework rule, AGENTS.md criterion and hook with its effective state", status: "implemented" },
  { namespace: "framework", verb: "show",    args: "<id> [--json]", summary: "Show one framework entry: state, deciding layer, owning skill(s), body location", status: "implemented" },
  { namespace: "framework", verb: "enable",  args: "<id>",          summary: "Enable a framework rule/criterion/hook (writes .sidekicks/config/settings/<kind>.yaml)", status: "implemented" },
  { namespace: "framework", verb: "disable", args: "<id>",          summary: "Disable a framework rule/criterion/hook; refuses every safety-floor id", status: "implemented" },
  { namespace: "framework", verb: "check",   args: "<id> [--quiet]", summary: "Predicate form for hook gates — exit 0 when enabled, 1 when disabled", status: "implemented" },
  { namespace: "framework", verb: "sync",    args: "[--check] [--prune] [--split] [--json]", summary: "Materialise .sidekicks/config/settings/ so every toggleable entry is listed (--check = read-only drift check; --split migrates the pre-split framework.yaml monolith)", status: "implemented" },
  { namespace: "framework", verb: "doctor",  args: "[--json]",      summary: "Registry/wiring drift check (missing bodies, unregistered or unwired hooks, floor mismatch, unlisted entries)", status: "implemented" },
  { namespace: "framework", verb: "config",  args: "<skill> [--json] [--reveal] | --list", summary: "Resolve a skill's config (alias of `config get` for the block that skill declares); credentials masked", status: "implemented" },
  { namespace: "config",   verb: "get",      args: "<block>[.<key>] [--json] [--reveal]", summary: "Effective value of one config block in the active scope, with the layer that decided each key", status: "implemented" },
  { namespace: "config",   verb: "list",     args: "[--json] [--family <f>] [--live]", summary: "Every registered config block grouped by its family file, with owners, readers and resolution rules", status: "implemented" },
  { namespace: "config",   verb: "where",    args: "<block> [--json]", summary: "Which file to edit for a block, and which files it currently resolves from, per scope", status: "implemented" },
  { namespace: "config",   verb: "set",      args: "<block>.<key> <value> [--secret] [--root] [--raw] [--json]", summary: "Mediated write: routes a credential to the git-ignored secret file and everything else to the committed family file", status: "implemented" },
  { namespace: "config",   verb: "sync",     args: "[--scope <name>] [--only a,b] [--dry-run] [--check] [--refresh] [--prune] [--json]", summary: "Rescan every installed skill and document its declared blocks in the scope's family files (written INERT, so they keep resolving to the skill's defaults); also materialises the settings half. --dry-run prints the plan (exit 0); --check is the CI gate (non-zero on a gap)", status: "implemented" },
  { namespace: "config",   verb: "migrate",  args: "<scope> | --all [--dry-run] [--prune] [--from-retired] [--json]", summary: "Split a scope's legacy config.yaml into family files + secret siblings, proving every block resolves identically (--from-retired re-splits from an already-retired monolith)", status: "implemented" },
  { namespace: "config",   verb: "example",  args: "<family|block> [--secrets] [--json]", summary: "Print a starting family file, or the git-ignored secret skeleton a fresh clone has to fill in", status: "implemented" },
  { namespace: "config",   verb: "doctor",   args: "[--json] [--scope <name>]", summary: "Config health gate: duplicate blocks, credentials in committed files, undeclared blocks, unknown family files", status: "implemented" },
  { namespace: "skill",    verb: "list",     args: "[--json] [--needs-manifest]", summary: "Inventory every skill with its dependency-manifest state and detected edge counts", status: "implemented" },
  { namespace: "skill",    verb: "show",     args: "<skill> [--json]",            summary: "One skill's declared vs detected dependencies, with file:line evidence per edge", status: "implemented" },
  { namespace: "skill",    verb: "manifest", args: "<skill> | --all [--check] [--apply] [--json]", summary: "Materialise a skill's dependency manifest from what the scanner finds (--check = read-only drift)", status: "implemented" },
  { namespace: "skill",    verb: "verify",   args: "[<skill>] [--json] [--strict]", summary: "Integrity check: is everything a skill declared present and unchanged (works on a lifted copy)", status: "implemented" },
  { namespace: "skill",    verb: "doctor",   args: "[<skill>] [--json] [--strict]", summary: "Dependency drift check: undeclared deps, escaped manifests, stale baselines, derived drift", status: "implemented" },
  { namespace: "skill",    verb: "heal",     args: "[<skill>] [--restore] [--apply] [--from <ref>] [--include-test] [--no-pip] [--json]", summary: "REPAIR: install declared Python deps into the root .venv and (--restore) put recorded bundle content back from git", status: "implemented" },
  { namespace: "skill",    verb: "export",   args: "<skill>... | --preset <p> [--output <path> | --destination <name>] [--with-deps] [--scope runtime|all] [--source-repo <url>] [--dry-run] [--strict] [--json]", summary: "Copy skills plus everything they declare into a skills-repository tree (writes files only — never commits or pushes)", status: "implemented" },
  { namespace: "skill",    verb: "destinations", args: "[<skill>] [--destination <name>] [--json]", summary: "Which skills are published to which configured skills repository, and whether each copy is still current", status: "implemented" },
  { namespace: "skill",    verb: "import",   args: "<skill>... | --all --from <path> [--adopt] [--layout <id>] [--rename <up>=<local>] [--into <tree>] [--list] [--apply] [--force] [--json]", summary: "Bring skills in from any repository that holds them, reconciled against the local baseline (--adopt converts a non-sidekicks layout)", status: "implemented" },
  { namespace: "skill",    verb: "advise",   args: "<skill>... [--from <path>] [--json]", summary: "What else a skill needs before it works: declared siblings (with what an absence costs), undeclared edges, and what cannot be installed", status: "implemented" },
  { namespace: "skill",    verb: "registry", args: "[<skill>] [--check] [--backfill --assume-imported] [--apply] [--json]", summary: "Registration profiles: what each imported skill came from, what its import turned on here, and whether the record still matches disk", status: "implemented" },
  { namespace: "skill",    verb: "offload",  args: "[<skill>] [--apply] [--restore] [--list] [--force] [--json]", summary: "PARK a skill into .sidekicks/skill-offloaded/ so discovery stops loading it — reversible, and NOT an uninstall", status: "implemented" },
  { namespace: "skill",    verb: "remove",   args: "<skill> [--destination <name>] [--apply] [--force] [--purge-profile] [--json]", summary: "UNINSTALL a skill: back it up, delete it, unwind its wiring (audit group, presets, category, settings, config) and retire its registry receipt — or, with --destination, retract its published copy; dry run unless --apply", status: "implemented" },
  { namespace: "skill",    verb: "repo",     args: "init <path> [--private] [--name <n>] [--remote <url>] [--json]", summary: "Scaffold the hand-authored half of a skills repository — licence, LAYOUT.md, README.md and one browse page per family, with the generated regions empty but marked; idempotent, and never writes catalog.yaml", status: "implemented" },
  { namespace: "core",     verb: "init",     args: "[--json] [--dry-run]", summary: "Seed (or re-seed) this workspace around the framework core mounted at .sidekicks-core/ — idempotent", status: "implemented" },
  { namespace: "core",     verb: "status",   args: "[--json] [--offline]", summary: "Which framework version this workspace runs, and whether the mount, wiring, overlay and push guard are healthy", status: "implemented" },
  { namespace: "core",     verb: "update",   args: "[--ref <tag|branch|sha>] [--json] [--dry-run]", summary: "Move the mounted core to another ref and re-apply everything derived from it (stages the gitlink, never commits)", status: "implemented" },
  { namespace: "core",     verb: "doctor",   args: "[--json] [--all]",     summary: "Gate on the mount's health: marker, shim, wiring, overlay, escaping links, push guard, enable map, node version; --all also composes framework/config/skill doctors (the release gate)", status: "implemented" },
  { namespace: "package",  verb: "create",   args: "[--output <path>] [--include-claude[=false]] [--include-gemini[=false]] [--include-agent[=false]] [--version-check] [--dry-run]", summary: "Assemble a clean, portable Sidekicks runtime package (upgrade-safe on an existing install)", status: "implemented" },
  { namespace: "package",  verb: "transfer", args: "<unit>... | --all [--output <path>] [--with-deps] [--version-check] [--dry-run]", summary: "Bundle individual lib subsystems and/or skills into a portable folder for reuse elsewhere", status: "implemented" },
  { namespace: "package",  verb: "preview",  args: "--output <path>", summary: "Alias for `package create --dry-run` — print the copy plan without writing", status: "implemented" },
  { namespace: "package",  verb: "versions", args: "", summary: "Ensure and report VERSION.json across all libs and skills", status: "implemented" },
  { namespace: "database", verb: "add",    args: "<name> (--file <path> | --env <alias> | --env <alias> --file <path>) [--schema <s>]... [--version <v>] [--force]", summary: "Ingest a combined schema .sql, explode into a per-table Markdown tree, and register in the manifest", status: "implemented" },
  { namespace: "database", verb: "list",   args: "[--json]",                                                                         summary: "List registered databases; flag orphaned on-disk dirs; --json for machine output",                  status: "implemented" },
  { namespace: "database", verb: "show",   args: "<name> [<version>]",                                                               summary: "Print metadata + resolved absolute source path and exploded tree for one entry",                     status: "implemented" },
  { namespace: "database", verb: "remove", args: "<name> [<version>] [--purge] [--keep-files]",                                      summary: "Deregister from manifest (keeps files by default); --purge to delete the artifact directory",        status: "implemented" },
  { namespace: "memory",   verb: "add",    args: "<name> [--type decision|context|reference|convention|rule] --description <d> [--category <c>] [--rule] [--source <durable>] [--snapshot <path> [--snapshot-lines A-B]] [--link <rel>:<slug>]… [--what <w>] [--why <y>] [--alt <a>] [--body <b>] [--agent <ag>] [--force]", summary: "Register an entry in the central store's active namespace: action --category (default general), --rule for a body that always loads when its category fires, a DURABLE --source (commit:<sha> | journal:<id> | evidence/… | committed path — artifacts/runs/ and absolute paths are refused; --snapshot copies the decisive content into evidence/ and anchors there), typed --link edges; regenerates MEMORY.md + index.json + graph.json", status: "implemented" },
  { namespace: "memory",   verb: "append", args: "<name> [--agent <ag>] --line <text>",                                                             summary: "Append ONE line to an existing entry's body deterministically (frontmatter and created: preserved; repairs embedded-frontmatter damage on touch) — the diary-buffer append path", status: "implemented" },
  { namespace: "memory",   verb: "show",   args: "<name> [--json] [--local] [--trace] [--agent <ag>]",                                              summary: "Print one local-memory entry (a project falls back to inherited root; --local = active scope only; --trace also resolves the lineage anchor)", status: "implemented" },
  { namespace: "memory",   verb: "list",   args: "[--json] [--local] [--compact] [--category <c>] [--namespace <ns>] [--agent <ag>]",               summary: "List effective entries from the central index (a project shows its own + inherited root; --local = active scope only)", status: "implemented" },
  { namespace: "memory",   verb: "map",    args: "[--json] [--all] [--local] [--agent <ag>]",                                                       summary: "The compact category map — per category: entry count + rule count. The ONLY thing a session loads at start; bodies come later via 'memory pack <category>'", status: "implemented" },
  { namespace: "memory",   verb: "query",  args: "<term-or-category> [--related] [--limit N] [--all] [--local] [--agent <ag>] [--json]",            summary: "Retrieval over the ONE central index.json: category match, then slug/description scan, then a bounded body sweep; --related expands one graph hop (declared edges first)", status: "implemented" },
  { namespace: "memory",   verb: "pack",   args: "<category> [--agent <ag>] [--local] [--json]",                                                    summary: "Emit one scenario pack: every RULE body in the category verbatim + index lines for the rest, merged over the namespace chain (project wins; --agent wins over that). The unit a trigger injects", status: "implemented" },
  { namespace: "memory",   verb: "graph",  args: "[<slug>] [--depth N] [--json]",                                                                  summary: "Knowledge-graph neighborhood of one entry (declared edges before harvested before inferred), or whole-graph stats with no slug", status: "implemented" },
  { namespace: "memory",   verb: "link",   args: "<from> <rel> <to> [--remove] [--agent <ag>]",                                                     summary: "Add or drop one DECLARED graph edge (derived-from|supersedes|relates|applies-to|blocks) in the source entry's frontmatter", status: "implemented" },
  { namespace: "memory",   verb: "triggers", args: "<list|set|reset> [<category>] [--skills a,b] [--verbs a,b] [--keywords a,b] [--json]",          summary: "Manage .sidekicks/memory/triggers.yaml — which skills, CLI verbs and keywords fire which category's pack", status: "implemented" },
  { namespace: "memory",   verb: "export", args: "<namespace> [--dir <path>] [--json]",                                                             summary: "Emit one namespace as a portable folder (entries + filtered index) for a project leaving the workspace", status: "implemented" },
  { namespace: "memory",   verb: "import", args: "<dir> [--namespace <ns>] [--force] [--json]",                                                     summary: "Ingest a folder produced by 'memory export' into a namespace of the central store", status: "implemented" },
  { namespace: "memory",   verb: "doctor", args: "[--json]",                                                                                       summary: "Report conflicted entries and unreviewed unions, an unregistered merge driver, dangling graph edges, superseded chains, oversized rule budgets and evidence, and any DORMANT pre-central legacy store still on disk", status: "implemented" },
  { namespace: "memory",   verb: "remove", args: "<name> [--agent <ag>] [--force]",                                                                 summary: "Delete one local-memory entry; edges that pointed at it survive as dangling for 'memory doctor' to report", status: "implemented" },
  { namespace: "memory",   verb: "rebuild", args: "[--if-stale] [--json]",                                                                          summary: "Regenerate the central store's three faces — MEMORY.md, index.json, graph.json — from on-disk entry frontmatter (self-heal after manual edits); --if-stale is a no-op when the committed fingerprint still matches the entry files", status: "implemented" },
  { namespace: "memory",   verb: "merge",  args: "<install|status|uninstall|driver> [--json]",                                                      summary: "The git merge driver that makes a memory merge conflict-free: entries merge field-by-field (links union, rule true wins, earliest created, body unioned and flagged when it diverges) and the derived faces are regenerated from the merged entries. `driver` is invoked BY git, never by hand; registration lives in .git/config and self-heals on every CLI run (SIDEKICKS_MEMORY_MERGE=off opts out)", status: "implemented" },
  { namespace: "memory",   verb: "resolve", args: "[<name>] [--all] [--strategy union|ours|theirs] [--accept] [--dry-run] [--json]",                summary: "Repair entries that already carry git conflict markers (a merge done before the driver was registered, or by another tool), and clear a merge_review flag with --accept once the union has been read", status: "implemented" },
  { namespace: "artifacts", verb: "register", args: "<skill> <slug> [field=value ...]",                                             summary: "Write/merge a run's run.json header (status/title/jira_card/goal/exit_check); co-located, never touches the index", status: "implemented" },
  { namespace: "artifacts", verb: "child",    args: "<parent-skill> <parent-slug> <child-key> [field=value ...] [--remove] [--bump-attempts]", summary: "Upsert one subtask row in the parent's subtasks[] (dynamic expansion, verdict, lineage); bubbles parent updated_at", status: "implemented" },
  { namespace: "artifacts", verb: "rebuild",  args: "",                                                                             summary: "Rebuild the derived index.json + ARTIFACTS.md by scanning all roots (project + service repos); infers legacy headers", status: "implemented" },
  { namespace: "artifacts", verb: "list",     args: "[--skill <s>] [--status <st>] [--json]",                                       summary: "List Jira artifact runs (scan-on-read); filter by skill/status; --json for machine output",         status: "implemented" },
  { namespace: "artifacts", verb: "show",     args: "<slug> [--skill <s>] [--json]",                                                summary: "Show one run's manifest, subtask tree, and exit_check; deterministic disambiguation across skills", status: "implemented" },
  { namespace: "artifacts", verb: "timeline", args: "[--json]",                                                                     summary: "Chronological view of every Jira run across the project and its service repos, newest first",        status: "implemented" },
  { namespace: "artifacts", verb: "scan",     args: "[--json]",                                                                     summary: "Scan the whole repo for every artifact type and write the consolidated .sidekicks/artifacts-inventory.{json,md}", status: "implemented" },
  { namespace: "artifacts", verb: "archive",  args: "<path> [--force] | --done [--dry-run] | --stale [--older-than <days>] [--force] [--dry-run]", summary: "Archive one artifact folder into its scope's archived/ mirror (git mv, staged); --done archives every finished run repo-wide; --stale archives every orphaned run older than <days> (default 7); refuses an active run without --force", status: "implemented" },
  { namespace: "artifacts", verb: "restore",  args: "<path>",                                                                       summary: "Move an artifact folder back out of artifacts/archived/ to its live location (inverse of archive)", status: "implemented" },
  { namespace: "cli-executor", verb: "register", args: "<name> [--binary <exe>] [--invoke '<a,{brief}>'] [--probe '<a>'] [--transport print-mode|json] [--sandbox <lvl>] [--brief-stdin] [--usage-exposed] [--disabled] [--description <d>] [--model-high <id>] [--model-mid <id>] [--model-low <id>] [--specialties '<a,b,c>'] [--model-specialties-high '<a,b>'] [--model-specialties-mid '<a,b>'] [--model-specialties-low '<a,b>']", summary: "Register/update an external agent CLI (generic, no adapter needed) so the executor family delegates to it without guessing; re-annotate a built-in with --disabled; set the per-complexity-tier model map with --model-high/mid/low; declare task specialties the orchestrator routes against with --specialties; pair each model tier with the jobs it is best at via --model-specialties-<tier>", status: "implemented" },
  { namespace: "cli-executor", verb: "list",     args: "[--json]",                                                                   summary: "Show the effective executor set for the active scope (built-ins merged with the on-disk registry)", status: "implemented" },
  { namespace: "cli-executor", verb: "remove",   args: "<name>",                                                                     summary: "Drop a registered executor from the scope-resolved registry (disable a built-in via register --disabled)", status: "implemented" },
  { namespace: "cli-executor", verb: "route",    args: "[set <name>... | clear | skill [set <task-kind> <name>... [--avoid '<a,b>'] [--note '<why>'] | remove <task-kind>]]", summary: "Manage the routing policy: the global preference chain (set/clear) AND per-task-kind recommendations ('route skill set image-generation antigravity codex --avoid claude') the orchestrator consults to pick the best-fit executor for a job", status: "implemented" },
  { namespace: "agent", verb: "create",    args: "<name> --specialty <s> --categories <a,b> [--cli claude|codex|gemini|antigravity] [--role orchestrator|worker] [--model <tier|id>] [--persona <s>] [--mission <s>] [--goals \"a;b\"] [--expertise \"a;b\"] [--principles \"a;b\"] [--routines \"a;b\"] [--output-contract <s>] [--work-dir <path>] [--attach <cat,cat>] [--force]", summary: "Scaffold a named persistent agent (.sidekicks/agents/<name>/): committed charter, a memory namespace in the central store, git-ignored runtime mailbox; --attach names the memory categories whose HARD RULES load at every wake; prints the bootstrap prompt", status: "implemented" },
  { namespace: "agent", verb: "amend",     args: "<name> --patch-file=<repo-relative-yaml> --dry-run|--apply [--json]", summary: "Review/apply a lossless instruction-only charter patch; preserves structural fields and all agent state", status: "implemented" },
  { namespace: "agent", verb: "list",      args: "[--json] [--category <c>]",                                                summary: "Roster: every charter merged with live presence (fresh/stale/offline) + inbox depths (scan-on-read, no index)", status: "implemented" },
  { namespace: "agent", verb: "show",      args: "<name> [--json]",                                                          summary: "One agent's charter, presence, control stage, inbox counts, and recent completed messages",           status: "implemented" },
  { namespace: "agent", verb: "start",     args: "<name> [--role orchestrator|worker] [--cli claude|codex|gemini|antigravity] [--model <tier|id>] [--print] [--spawn] [--headless] [--wait-online[=90]]", summary: "Launch a new terminal session for the agent using its charter CLI (or a one-off --cli override) + role-appropriate bootstrap prompt + resolved --model flag (--print never spawns; --spawn forces the window even from inside VS Code but is REFUSED with exit 2 when the session has no GUI to host one — use --headless there; auto otherwise; --headless starts the detached delegate runner instead of a window; --wait-online polls real presence and exits 2 if the agent never heartbeats — a window opening is never proof it came online)", status: "implemented" },
  { namespace: "agent", verb: "delegate",  args: "<name> [--once] [--status] [--interval 2] [--max-runtime 3600] [--rotate-after 20] [--rotate-context 180000] [--settle 3] [--requeue-limit 3] [--permission-mode <m>] [--model <tier|id>] [--full-context] [--force]", summary: "Headless always-on runner: watches inbox/new and wakes a non-interactive agent-CLI session (cwd = repo root — skills, subagents, and CLI verbs intact) to drain it; primes each wake with the conversation-context block, resumes the wake session until its resident context passes --rotate-context, honors 'agent stop', keeps the comms daemons alive (adapters: claude, codex, antigravity — claude and codex resume their wake session, an antigravity wake is always fresh because agy has none); claude wakes run lean by default (--strict-mcp-config, --setting-sources project, --exclude-dynamic-system-prompt-sections) — --full-context restores the pre-lean context for debugging", status: "implemented" },
  { namespace: "agent", verb: "daemon",    args: "<sleep|status|wake|reset|reconcile|check> <agent> [--action <decider-action>|--seconds <n>] [--mission <MIS-id|slug>] [--reason=<t>] [--session <sid>] [--dry-run] [--json]", summary: "Delegate PACEMAKER control for one lane (the delegate's own clock, not a process): `sleep` records the ONE-SHOT budget the woken agent wants before its next self-injected mission tick — a decider action name resolves to seconds from .sidekicks/config.yaml (agent_daemon), per declared mission first, so the number never lives in a skill — clamped to the configured min/max and reverting to the default afterwards; `status` prints the effective budget, the pending request, the declared missions and whether a delegate is even there to consume them; `wake` arms the next idle tick to fire at once; `reset` drops a pending request; `reconcile` opens the L7 journal missions declared in config, bound to their minted MIS- ids through a runtime ledger so it is safe to re-run — it refuses past the journal's live-mission cap rather than forcing, and never closes anything; `check` VALIDATES the config block deterministically and exits 2 on anything the operator wrote that the pacemaker is silently discarding — unknown keys that fall back to defaults, sleep_by_action values clamped to death by min/max, a column-0 line mid-block that truncates the reader's slice, yaml anchors/aliases/tags that void the whole block, a lane declared under a name with no charter, and reconcile's slug-ledger duplicate-mission risk. NOT the fleet comms daemons — those stay under `agent scheduler|telegram|serve`", status: "implemented" },
  { namespace: "agent", verb: "pack",      args: "<list|show|install|status> [<pack-id>] [--dry-run] [--json]", summary: "OPTIONAL agent packs — versioned crews of portable charters that SHIP inside a framework core and are never installed for you automatically (`core init`/`core update` write no agent). `list`/`show` report each pack's version, per-agent presence and per-skill dependency state (available / missing-but-installable / unavailable); `install` validates the manifest and every charter, refuses BEFORE writing anything when a required skill is absent (printing the exact `skill import` commands), then creates only the agents that are missing — an agent you already have or have edited is never overwritten, and a repeat run writes nothing; `status` grades a pack ready | degraded | not-installed | invalid and exits 2 on anything but ready. Nothing here reaches the network or downloads a skill", status: "implemented" },
  { namespace: "agent", verb: "retire",    args: "<name> [--force]",                                                     summary: "Flip charter status to retired (keeps memory/history); refuses while live or with unclaimed work unless --force", status: "implemented" },
  { namespace: "agent", verb: "send",      args: "<to> --from <n> [--kind task|reply|signal] [--category <c>] [--priority <n>] [--goal <g>] [--acceptance \"a;b\"] [--options \"a;b\"] [--work-dir <p>] [--isolation worktree|shared] [--reply-to <id>] [--thread <id>] [--body-file <p>] [--json]", summary: "Drop a message into an agent's inbox/new (a task must match the recipient's charter categories); --thread binds it to a conversation without touching the delegation chain; --options offer choices (telegram renders them as tap-to-answer buttons)",     status: "implemented" },
  { namespace: "agent", verb: "inbox",     args: "<name> [--state new|claimed|done] [--json]",                               summary: "List one agent's messages in a state, oldest-first",                                                status: "implemented" },
  { namespace: "agent", verb: "claim",     args: "<name> [<id>] --session <sid>",                                            summary: "Atomically claim a message (rename new/→claimed/, race-safe); prints the message JSON; exit 2 = nothing claimable", status: "implemented" },
  { namespace: "agent", verb: "complete",  args: "<name> <id> --status done|failed [--summary <s>] [--branch <b>] [--deliverable <p>]... [--option <label>]... [--no-reply]", summary: "Stamp the result, move claimed/→done/, auto-reply to the original sender's inbox; --option offers choices back to the sender (telegram renders them as tap-to-answer buttons)",                  status: "implemented" },
  { namespace: "agent", verb: "heartbeat", args: "<name> --session <sid> [--state standby|working] [--task <id>]",           summary: "Upsert presence; exit 4 when a DIFFERENT live session owns this agent",                             status: "implemented" },
  { namespace: "agent", verb: "wait",      args: "<name> --session <sid> [--timeout 540] [--interval 2]",                    summary: "BLOCK until work arrives (exit 0), timeout (2), control stop (3), or foreign session (4); heartbeats every tick", status: "implemented" },
  { namespace: "agent", verb: "stop",      args: "<name>|--all [--stage stop|pause|resume]",                                 summary: "Write the control gate from any session — the standby loop honors it within one wait tick; --all gates every non-retired agent at once", status: "implemented" },
  { namespace: "agent", verb: "serve",     args: "[--port 7787] [--bind 0.0.0.0] [--token <t>]",                             summary: "Local-network HTTP bridge: other terminals on the LAN read the roster and send into mailboxes (bearer token + private-IP-only guard; runs until Ctrl-C)", status: "implemented" },
  { namespace: "agent", verb: "bridge",    args: "<list|show|inbox|send> [<agent>] --host <ip:port> [--token <t>] [send flags…]", summary: "Client for a remote `agent serve` bridge — send/list/show/inbox against another machine on the same network (env: SIDEKICKS_BRIDGE_HOST/TOKEN)", status: "implemented" },
  { namespace: "agent", verb: "telegram",  args: "<setup|status|serve> [--token <bot>] [--bot <id>] [--chat <id>] [--topic <n>] [--target <agent>] [--lane <id>] [--once] [--json]", summary: "Telegram relay (external network): long-polls the user's bot(s), routes chat messages into agent mailboxes (acknowledged immediately in the chat), posts completions back HTML-formatted with inline choice buttons. A channel table maps (bot, chat, forum topic) → target orchestrator, so several lanes each get their own surface and their own relay mailbox; --lane writes one channel row, status --json is the machine-readable table (never includes a token)", status: "implemented" },
  { namespace: "agent", verb: "routine",   args: "<add|list|remove|enable|disable|run> <agent> [<id>] [--id <slug>] [--when daily|weekly|once|cron|every] [--at HH:MM|YYYY-MM-DDTHH:MM] [--cron \"m h dom mon dow\"] [--every 30m|2h|1d] [--days mon,wed,fri] [--category <c>] [--goal <g>]|[--sequence <path>] [--work-dir <p>] [--acceptance \"a;b\"] [--priority <n>] [--grace <minutes>] [--deliver telegram] [--note <s>] [--disabled] [--force] [--dry-run] [--json]", summary: "Schedule standing work for an agent: recurring (daily / weekdays / numeric 5-field cron / fixed interval on the midnight grid) or a one-shot date-time job, firing an inline prompt or a command-sequence into the agent's mailbox (Asia/Bangkok wall clock; committed); --deliver telegram routes the RESULT to the user's chat via the relay; add --dry-run previews the next fires and writes nothing", status: "implemented" },
  { namespace: "agent", verb: "scheduler", args: "<serve|status|stop> [--interval 30] [--once] [--json]",                        summary: "Fleet-wide routine scheduler daemon: ticks the clock, fires every agent's due routines into its mailbox through the validated send path, honours a grace window for missed occurrences, and never fires the same occurrence twice", status: "implemented" },
  { namespace: "agent", verb: "office",    args: "[--port 4690] [--bind 127.0.0.1] [--once] [--json] [--replace] [--open]", summary: "Read-only live web dashboard over the persistent-agent office: roster + presence, activity feed, conversation threads, dry-run plan gate, scheduler, comms liveness — localhost by default (token required on a non-loopback bind), SSE live updates, singleton per repo; --once prints the JSON snapshot and exits", status: "implemented" },
  { namespace: "agent", verb: "thread",    args: "<resolve|append|context|show|list|search|digest|close|prune|rebuild> <agent> [<thread-id>] [--channel <c>] [--chat <id>] [--reply-to-message <n>] [--idle-gap 480] [--new] [--role user|agent] [--text=<t>] [--text-file=<p>] [--msg-id <id>] [--channel-message-id <n>] [--turns 6] [--max-bytes 3000] [--from <seq>] [--limit 20] [--set=<s>] [--set-file=<p>] [--auto] [--open] [--json]", summary: "Conversation memory: one append-only verbatim transcript per thread (git-ignored runtime/threads/), a durable digest per thread, and the context block a session is primed with — threads are bound by an idle gap or explicitly (/new), and text flags need the --key=value form", status: "implemented" },
  { namespace: "journal", verb: "log",      args: "[<agent>] [--task <id>] [--since 7d] [--limit 50] [--json]",                  summary: "L0 event log: the append-only row `agent complete` writes for every finished task (the spine every other layer joins to)", status: "implemented" },
  { namespace: "journal", verb: "retro",    args: "add <agent> --task <id> --status done|failed --problems <s> [--assignment <s>] [--improve-self <s>] [--do <s>] [--dont <s>] | list [<agent>] [--since 7d] [--json] | show <id>", summary: "L1 per-assignment retrospective: what went wrong, what to improve, what to do and not do next time", status: "implemented" },
  { namespace: "journal", verb: "incident", args: "add <agent> --subject <s> --what <s> [--evidence <s>] [--cause <s>] [--handled <s>] [--prevent <s>] [--task <id>] [--severity low|medium|high] [--promote] | list [--status open|resolved] [--json] | resolve <id> [--how <s>] | show <id>", summary: "L2 incident: one thing that broke, with evidence; --promote also opens the tracked L3 issue", status: "implemented" },
  { namespace: "journal", verb: "issue",    args: "add --title <s> [--from-incident <id>] [--owner <agent>] [--severity low|medium|high] [--detail <s>] | list [--status open|ack|fixed|wontfix] [--json] | show <id> | ack <id> | close <id> --resolution <s> [--wontfix]", summary: "L3 issue tracked to closure — the layer that makes a problem survive past the moment it was noticed", status: "implemented" },
  { namespace: "journal", verb: "improve",  args: "add <agent> --target charter|skill|routine --title <s> --change <s> --why <s> [--field <f>] | list [<agent>] [--status proposed|applied|rejected] [--json] | show <id> | apply <id> | reject <id> --why <s>", summary: "L5 agent self-improvement: a proposed change to an AGENT's charter (skills go through sk-self-improve); apply is gated on the charter's improvement.enabled", status: "implemented" },
  { namespace: "journal", verb: "diary",    args: "write <agent> [--day <s>] [--incidents <s>] [--well <s>] [--improve <s>] [--tomorrow <s>] [--from-buffer] | show <agent> [<YYYY-MM-DD>]",                     summary: "L4 daily self-review, one per agent per day (a second write the same day appends an addendum); the boundary that pushes the store", status: "implemented" },
  { namespace: "journal", verb: "lesson",   args: "add <agent> --title <s> --body <s> [--context <s>] [--tags a,b] | list [<agent>] [--status active|retired] [--limit N] [--json] | show <LES-id> | retire <LES-id> --why <s>", summary: "L6 fleet lesson pool: distilled rules ANY agent should know — bounded (50 active, add refuses past the cap), newest ride every delegate wake as the FLEET LESSONS block", status: "implemented" },
  { namespace: "journal", verb: "mission",  args: "open|propose <agent> --title=<s> --why=<s> [--goal=<s>|--goal-file=<p>] [--dod=<s>] [--priority 1-5] [--due YYYY-MM-DD] [--tags a,b] [--related <id>] [--start] [--standing] [--force] | approve|reject <MIS-id> [--reason=<s>] | plan <MIS-id> --step=<title>… [--after sN] [--lane agent:<n>|subagent:<n>|handoff:<skill>|user] [--gate <kind>] [--acceptance=<s>] [--drop sN --reason=<s>] | event <MIS-id> --type <t> [--step sN] [--evidence=<p>] [--note=<s>] | verify <MIS-id> --step sN --verdict pass|fail [--evidence=<p>] [--reason=<s>] | classify <agent> --text=<s> | resolve <MIS-id> --resolution accept|revise|shelve | close <MIS-id> --outcome done|abandoned --summary=<s> | next <agent> [--mode consolidate] [--now <ts>] | list [<agent>] [--status <s>] [--all] | show <MIS-id> [--events] | doctor [<agent>] [--json]", summary: "L7 mission: an agent's own standing work — a goal, its plan steps, its verdicts, its outcome. Current status is FOLDED from an append-only per-node event log (mission.md is immutable), so several machines never rewrite one file. `--standing` (open only, no-op on propose) keeps a mission self-planning its next step batch toward the SAME goal forever, instead of falling through to propose_goal once its steps are all verified — only an explicit `mission close` or disabling the firing routine ends it. `next` is the DECIDER a memory-less wake obeys: it returns exactly ONE action (verify_step | resume_blocked | execute_step | plan_steps | await_approval | propose_goal | consolidate_day | idle), writes nothing, and exits 0 even when idle", status: "implemented" },
  { namespace: "journal", verb: "report",   args: "[--agent <a>] [--since 7d] [--json]",                                       summary: "Cross-layer roll-up: tasks joined to their retrospectives, incidents, issues and improvement proposals",  status: "implemented" },
  { namespace: "journal", verb: "doctor",   args: "[--agent <a>] [--since 7d] [--json]",                                         summary: "Gap report: completed tasks with no retrospective, unpromoted incidents, stale open issues, unpushed commits", status: "implemented" },
  { namespace: "journal", verb: "rebuild",  args: "[--json]",                                                                    summary: "Re-derive the store's index.jsonl from on-disk entry frontmatter (self-heal after manual edits)",     status: "implemented" },
  { namespace: "journal", verb: "push",     args: "[--force]",                                                                   summary: "Push the journal store to its remote (the explicit boundary; --force pushes even under push:never)",  status: "implemented" },
]);

// Derived once from VERBS (first-appearance order) — the single source for the namespace
// topic set, so cli.mjs's --help topic check and the "Namespaces:" listing below never
// drift out of sync with each other or with a newly-registered namespace.
export const NAMESPACES = Object.freeze([...new Set(VERBS.map((v) => v.namespace))]);

/**
 * Render help text, optionally scoped to a single namespace.
 *
 * @param {string | null | undefined} [topic] - Namespace to scope help to (one of NAMESPACES).
 * @returns {string} Formatted help text (no trailing newline — caller adds one if needed).
 */
export function renderHelp(topic) {
  const lines = [];

  if (!topic) {
    // Top-level help — list all namespaces and verbs.
    lines.push("sidekicks — zero-dependency agent substrate");
    lines.push("");
    lines.push("Usage: sidekicks <namespace> <verb> [args] [flags]");
    lines.push("");
    lines.push("Flags:");
    lines.push("  --help        Show this help message");
    lines.push("  --version     Print the version and exit");
    lines.push("  --verbose     Show verbose output (stack traces on errors)");
    lines.push("");
    lines.push("Namespaces:");
    lines.push("  project       Manage projects");
    lines.push("  service       Manage services within a project");
    lines.push("  branch        Manage git branches of the active scope's repo");
    lines.push("  scope         Inspect the active scope's resolved paths");
    lines.push("  index         Rebuild, show, and resolve the structural index");
    lines.push("  framework     Framework rules, criteria, hooks and per-skill config resolution");
    lines.push("  skill         Declare, inspect, verify and repair each skill's runtime dependencies");
    lines.push("  package       Assemble, transfer, and version portable Sidekicks packages");
    lines.push("  database      Register and inspect project database schemas");
    lines.push("  memory        Register and read scope-resolved local-memory entries");
    lines.push("  artifacts     Discover, write, list, inventory, and archive skill run-state & artifacts");
    lines.push("  cli-executor  Register the external agent CLIs the executor family delegates to");
    lines.push("  agent         Named persistent agents: registry, file mailbox, presence, standby wait");
    lines.push("  journal       Layered work journal: tasks, retros, incidents, issues, missions");
    lines.push("");

    for (const ns of NAMESPACES) {
      const verbs = VERBS.filter((v) => v.namespace === ns);
      lines.push(`${ns} commands:`);
      for (const v of verbs) {
        const argsStr = v.args ? ` ${v.args}` : "";
        const pad = 28;
        const left = `  ${v.verb}${argsStr}`;
        const spacer = " ".repeat(Math.max(1, pad - left.length));
        lines.push(`${left}${spacer}${v.summary} (${v.status})`);
      }
      lines.push("");
    }
  } else {
    // Namespace-scoped help.
    const verbs = VERBS.filter((v) => v.namespace === topic);
    lines.push(`sidekicks ${topic} commands:`);
    lines.push("");
    lines.push(`Usage: sidekicks ${topic} <verb> [args] [flags]`);
    lines.push("");
    for (const v of verbs) {
      const argsStr = v.args ? ` ${v.args}` : "";
      const pad = 28;
      const left = `  ${v.verb}${argsStr}`;
      const spacer = " ".repeat(Math.max(1, pad - left.length));
      lines.push(`${left}${spacer}${v.summary} (${v.status})`);
    }
    lines.push("");
    lines.push(`Run 'sidekicks --help' for the full verb listing.`);
  }

  return lines.join("\n");
}
