// lib/skill-registry/profile.mjs
// The registration profile for one IMPORTED skill — render and parse, no I/O.
//
// A RECEIPT IS NOT A REGISTRY, and this file exists only because that distinction holds.
//
// Two neighbouring modules refuse to store what this one stores, and both are right about their own
// question. `lib/skill-lifecycle/destinations.mjs` answers "is the published copy current?" — every
// input still exists (catalog.yaml, meta/<skill>/origin.yaml, the local bundle{}), so recording the
// answer would only add a fifth thing to keep in step. `lib/skill-lifecycle/import.mjs` answers "did
// the two sides diverge?" — and `bundle{}` already IS the blessed baseline.
//
// Removal asks a different question: WHAT DID THIS REPO CHANGE WHEN IT TOOK THIS SKILL IN? That is a
// fact about an EVENT, and the event leaves no derivable trace. Afterwards, `rules.yaml` cannot say
// whether a criterion was enabled BY that import or was already here; `audit-groups.yaml` cannot say
// the group was a judgement made FOR it; a converted foreign folder looks exactly like a
// hand-authored one; and the source commit that produced the bytes is gone the moment the clone is.
// Nothing on disk holds any of it. So the profile records those and nothing else it could look up.
//
// Four guarantees keep it from rotting into a hand-maintained fifth source of truth:
//   1. Generated only — the header says so, and no field is ever hand-written.
//   2. The CLI is the sole writer (Rule 1).
//   3. `skill registry --check` recomputes every MIRRORED field from disk; the filesystem wins.
//   4. Nothing here exposes a derivable fact. There is no isInstalled(), no listSkills() —
//      discoverSkills() and `skill destinations` stay authoritative.
//
// Zero npm dependencies — node:* + lib/ back-edges only.

import { yamlLine } from '../skill-package/portable.mjs';
import { parse, findPoison } from '../yaml-subset/yaml.mjs';
import { SidekicksError, EXIT_VALIDATION } from '../sk-cli/errors.mjs';

export const PROFILE_SCHEMA = 1;

/**
 * Recorded because it cannot be derived once the import is over.
 * Read this list as the answer to "why does this file exist at all".
 */
export const RECORDED_KEYS = Object.freeze([
  'source', 'upstream', 'adapter', 'enabled_here', 'licence', 'imported_at', 'imported_by',
  'files', 'files_recorded_at', 'history', 'status', 'provenance',
]);

/** Mirrored from disk for legibility, and re-derived by `--check`. Never consulted as truth. */
export const MIRRORED_KEYS = Object.freeze(['mirror']);

/** What a field is set to when nobody can honestly know it. Distinct from absent, which reads as "none". */
export const UNKNOWN = 'unknown';

/**
 * Render one profile.
 *
 * Every scalar goes through `yamlLine`: one single-quoted line, apostrophes doubled, no block
 * scalars, `&`/`*` neutralised. Those three constraints are each a bug this repo has already been
 * bitten by, and the yaml-subset reader enforces them (docs/guide/skill-architecture.md §6).
 *
 * @param {object} f - facts; see RECORDED_KEYS
 * @returns {string}
 */
export function renderProfile(f) {
  const L = [];
  L.push('# registration profile — the receipt for one imported skill.');
  L.push('#');
  L.push('# GENERATED by `sidekicks skill import`. Never hand-edit it (Rule 1): the CLI is the sole');
  L.push('# writer, and `sidekicks skill registry --check` re-derives every mirrored field from disk');
  L.push('# — where the two disagree, the filesystem is right and this file is stale.');
  L.push('#');
  L.push('# It records what the IMPORT did, which nothing on disk can reconstruct afterwards. What is');
  L.push('# already derivable — the bundle baseline, what is published where — is deliberately not here.');
  L.push('');
  L.push(`schema: ${PROFILE_SCHEMA}`);
  L.push(`skill: ${yamlLine(f.skill)}`);
  L.push(`status: ${yamlLine(f.status || 'installed')}`);
  L.push(`provenance: ${yamlLine(f.provenance || 'imported')}`);
  L.push('');

  L.push('# ── RECORDED (non-derivable) — the reason this file exists ──────────────────────────────');
  L.push('source:');
  L.push(`  kind: ${yamlLine(get(f.source, 'kind'))}`);
  L.push(`  destination: ${yamlLine(get(f.source, 'destination'))}`);
  L.push(`  remote: ${yamlLine(get(f.source, 'remote'))}`);
  L.push(`  commit: ${yamlLine(get(f.source, 'commit'))}`);
  L.push(`  branch: ${yamlLine(get(f.source, 'branch'))}`);
  L.push('upstream:');
  L.push(`  name: ${yamlLine(get(f.upstream, 'name'))}`);
  L.push(`  path: ${yamlLine(get(f.upstream, 'path'))}`);
  L.push(`  version: ${yamlLine(get(f.upstream, 'version'))}`);
  L.push(`  description: ${yamlLine(get(f.upstream, 'description'))}`);
  L.push('adapter:');
  L.push(`  layout: ${yamlLine(get(f.adapter, 'layout'))}`);
  L.push(`  converted: ${get(f.adapter, 'converted') === true}`);
  L.push(`  category: ${yamlLine(get(f.adapter, 'category'))}`);
  L.push(`  synthesized: ${yamlLine(get(f.adapter, 'synthesized'))}`);
  L.push('enabled_here:');
  L.push(`  framework_rules: ${yamlLine(get(f.enabled_here, 'framework_rules'))}`);
  L.push(`  config_blocks: ${yamlLine(get(f.enabled_here, 'config_blocks'))}`);
  L.push(`  hooks_requested: ${yamlLine(get(f.enabled_here, 'hooks_requested'))}`);
  L.push(`  repo_root_files: ${yamlLine(get(f.enabled_here, 'repo_root_files'))}`);
  L.push(`  audit_group: ${yamlLine(get(f.enabled_here, 'audit_group'))}`);
  L.push('licence:');
  L.push(`  declared: ${yamlLine(get(f.licence, 'declared'))}`);
  L.push(`  carried: ${yamlLine(get(f.licence, 'carried'))}`);
  L.push(`  not_carried: ${yamlLine(get(f.licence, 'not_carried'))}`);
  L.push(`imported_at: ${yamlLine(f.imported_at)}`);
  L.push('imported_by:');
  L.push(`  tool: ${yamlLine(get(f.imported_by, 'tool'))}`);
  L.push(`  cli_version: ${yamlLine(get(f.imported_by, 'cli_version'))}`);
  L.push('');

  L.push('# ── MIRRORED (derivable) — legibility and drift detection only ──────────────────────────');
  L.push('mirror:');
  L.push(`  tree: ${yamlLine(get(f.mirror, 'tree'))}`);
  L.push(`  version: ${yamlLine(get(f.mirror, 'version'))}`);
  L.push(`  manifest_present: ${get(f.mirror, 'manifest_present') === true}`);
  L.push(`  descriptor_present: ${get(f.mirror, 'descriptor_present') === true}`);
  L.push(`  file_count: ${Number(get(f.mirror, 'file_count') || 0)}`);
  L.push('');

  L.push('# ── AS-INSTALLED BASELINE (recorded) ────────────────────────────────────────────────────');
  L.push('# LF-normalized sha256 at the moment of import. Distinct from bundle{}, which a later');
  L.push('# `skill manifest --apply` re-records — this is what ARRIVED, so a removal can tell a file');
  L.push('# it brought from one added afterwards.');
  L.push(`files_recorded_at: ${yamlLine(f.files_recorded_at || 'import')}`);
  L.push('files:');
  for (const rel of Object.keys(f.files || {}).sort()) {
    L.push(`  ${rel}: ${yamlLine(f.files[rel])}`);
  }
  L.push('');
  L.push('history:');
  for (const h of f.history || []) {
    L.push(`  - at: ${yamlLine(h.at)}`);
    L.push(`    action: ${yamlLine(h.action)}`);
    L.push(`    detail: ${yamlLine(h.detail)}`);
  }

  const text = L.join('\n') + '\n';
  const poison = findPoison(text);
  if (poison) {
    throw new SidekicksError(
      `skill registry: refusing to write an unreadable profile for '${f.skill}': ${poison}`,
      EXIT_VALIDATION
    );
  }
  return text;
}

/** `obj?.key`, flattened to '' — a profile field is never undefined, only empty or `unknown`. */
function get(obj, key) {
  if (!obj || typeof obj !== 'object') return '';
  const v = obj[key];
  return v === null || v === undefined ? '' : v;
}

/**
 * Parse one profile. Errors are RETURNED, never thrown, except on text the reader cannot parse at
 * all — the same contract `parseManifest` keeps, so a single corrupt profile reports itself rather
 * than taking down a whole `registry --check` run.
 *
 * @param {string} text
 * @param {string} name
 * @returns {{profile: object|null, errors: string[]}}
 */
export function parseProfile(text, name) {
  let obj;
  try {
    obj = parse(text);
  } catch (err) {
    return { profile: null, errors: [`${name}: unparseable — ${err.message}`] };
  }
  if (!obj || typeof obj !== 'object') return { profile: null, errors: [`${name}: empty profile`] };

  const errors = [];
  if (Number(obj.schema) !== PROFILE_SCHEMA) {
    errors.push(`${name}: schema ${obj.schema} is not ${PROFILE_SCHEMA}`);
  }
  if (typeof obj.skill !== 'string' || !obj.skill) errors.push(`${name}: no skill name`);
  else if (obj.skill !== name) errors.push(`${name}: profile names a different skill '${obj.skill}'`);

  return { profile: obj, errors };
}
